let game_data = 
{
    "persona": [
        {
            "type": "",
            "name": "Student",
            "desc": "You're a student who lives in the town and studies at the local college. The college is great, but you especially enjoy all the outdoor places around town. <br>  <br> You would like to have more money and freedom but are unsure how to get them.\u200b You love going outdoors and doing nice things with friends and family, and prefer not to work too hard at the moment. <br>  <br> You hate older people telling you what to do and where to go, were they ever young? The state of the environment, everything seems to be messed up and getting worse. You worry deeply about your future and the state of the world.",
            "img": "student2.jpg",
            "local_url": "kb/persona/personas.html",
            "url": "https://arsinoe-serious-game.github.io/kb/persona/personas.html",
            "qr_code": "assets/persona/persona_0_qr.png"
        },
        {
            "type": "",
            "name": "Young Worker",
            "desc": "It's been a couple of years since you left education and have been finding your feet in the adult world of employment and responsibilities. <br>  <br> You like having a stable job with a decent wage and room to grow,\u200b having nice things to do when you're not at work, being able to get on, buy a nice flat with your partner and start putting down some roots.\u200b <br>  <br> You hate\u200b the lack of work opportunities, you want to get on and build a career. You're struggling to make ends meet and you seem to pay a lot of tax but not see much for it, given the state of the local environment, every thing looks tired and needs a good clean up.\u200b",
            "img": "single_worker.jpg",
            "local_url": "kb/persona/personas.html",
            "url": "https://arsinoe-serious-game.github.io/kb/persona/personas.html",
            "qr_code": "assets/persona/persona_0_qr.png"
        },
        {
            "type": "",
            "name": "Family",
            "desc": "You're a young parent with young children. Life is now more complicated and you're still learning how to handle everything.\u200b <br>  <br> You enjoy doing things with your family, knowing that your kids have a future in the town\u200b, and being able to unwind with your partner at the end of the day.\u200b <br>  <br> You dislike people and policies that are family unfriendly. You don't want excessive government intervention or pollution that may impact your family.",
            "img": "family.jpg",
            "local_url": "kb/persona/personas.html",
            "url": "https://arsinoe-serious-game.github.io/kb/persona/personas.html",
            "qr_code": "assets/persona/persona_0_qr.png"
        },
        {
            "type": "",
            "name": "Retiree",
            "desc": "You are a retired worker. You've spent your lifetime working hard, so at this age, you are expecting everything that is rightful for you. <br>  <br> You enjoy activities that suit an active senior citizen such as shopping, meeting friends,  entertaining. You like using public transport that is easy and stress-free.\u200b <br>  <br> You don't like changes that hurts you.\u200b You are annoyed when young people complain about \"it's hard now\" while you remember how tough it was when you were young, but it didn't affect you much.\u200b You have paid taxes all your life and think that retirees should not pay for extra taxes.\u200b",
            "img": "retiree.jpg",
            "local_url": "kb/persona/personas.html",
            "url": "https://arsinoe-serious-game.github.io/kb/persona/personas.html",
            "qr_code": "assets/persona/persona_0_qr.png"
        },
        {
            "type": "",
            "name": "Business owner",
            "desc": "You are a local business owner and have run it for years. The shop keeps you busy enough and financially secure, but not wealthy.\u200b <br>  <br> You like nice customers who make good purchases\u200b, tourists and holidaymakers who are keen to buy at your shop. You feel proubd to be a part of the local community\u200b. <br>  <br> You hate the mall outside town that takes your customers, high parking charges stopping people coming to town.\u200b The municipality needlessly changing things, you prefer things to stay as they are.",
            "img": "business_owner.jpg",
            "local_url": "kb/persona/personas.html",
            "url": "https://arsinoe-serious-game.github.io/kb/persona/personas.html",
            "qr_code": "assets/persona/persona_0_qr.png"
        },
        {
            "type": "",
            "name": "Politician",
            "desc": "You are a local politician who entered politics to fight injustice both locally and in the wider community. <br>  <br> You enjoy being a positive influence in the community, helping change things even when people do not want it, and keeping big companies and powerful people from abusing their power. <br>  <br> You hate people and organisations that don't understand that we are just tenants, not the permanent owners of the town. You also hate those who try to make quick money at the expense of hardworking citizens.",
            "img": "politician.jpg",
            "local_url": "kb/persona/personas.html",
            "url": "https://arsinoe-serious-game.github.io/kb/persona/personas.html",
            "qr_code": "assets/persona/persona_0_qr.png"
        }
    ],
    "resilience": [
        {
            "type": "EP",
            "name": "Economic Resilience Challenge",
            "heading-0": "What are economic resilience challenges?",
            "desc-0": "Economic resilience challenges arise when confidence in the economy declines. This manifests as reduced investment, company closures, job losses, and a general decrease in consumer spending. The severity of these challenges is determined by both their impact and duration; extreme events will have deeper and longer-lasting consequences than milder one.",
            "heading-1": "Minor Resilience Challenge",
            "heading-2": "Average Resilience Challenge",
            "heading-3": "Extreme Resilience Challenge",
            "desc-1": "A large local employer closes down. All of a sudden, many people are out of work and companies that rely on the closed company have a reduction in their turnover.",
            "desc-2": "Bad weather impacts the summer holiday season, leading to a decline in trade for many local businesses. Some companies are able to withstand, but for smaller ones that heavily rely on the summer season face potential closure due to substantial losses.",
            "desc-3": "Economic decisions in a country far, far, away for coping with a global credit crunch have restricted the access to capital for many international companies, forcing them to suspend their operations in the town. This has increased costs for goods and services and a general reluctance among residents to spend.",
            "outcome-heading": "Resilience Challenge Outcomes",
            "outcome-0": "The municipality's decisions have rendered the town particularly vulnerable to economic fluctuations. As businesses close and jobs disappear, residents lack adequate support systems, exacerbating an already difficult situation. Public sentiment is sharply critical of the municipality's economic resilience planning, with expectations that the mayor will likely resign.",
            "outcome-1": "The town has experienced some business failures and many residents are facing financial hardship due to the event. While acknowledging that the situation could have been worse, there's a widespread feeling that more proactive measures could have mitigated the impact. There's a sense that the municipality's planning fell short of expectations.",
            "outcome-2": "Although the event has had some impacts, they have been minor in nature with no major consequences, which is a significant relief to local businesses and residents. Many believe that the municipality's economic resilience planning was successful.",
            "outcome-3": "The economic event appears to have had a limited impact on the town, providing considerable relief to local businesses and residents. However, some are questioning whether the municipality may have overprepared for such events and if the town is able to cope with more extreme events.",
            "local_url": "kb/resilience/resilience_0.html",
            "url": "https://arsinoe-serious-game.github.io/kb/resilience/resilience_0.html",
            "qr_code": "assets/resilience/resilience_0_qr.png"
        },
        {
            "type": "BP",
            "name": "Biodiversity Resilience Challenge",
            "heading-0": "What are biodiversity resilience challenges?",
            "desc-0": "Challenges to biodiversity resilience occur when the plants and animals in an environment are threatened by outside factors. This commonly happens due to industrial pollution or the introduction of non-native flora and fauna.",
            "heading-1": "Minor Resilience Challenge",
            "heading-2": "Average Resilience Challenge",
            "heading-3": "Extreme Resilience Challenge",
            "desc-1": "A storage failure at a local dairy farm resulted in milk contaminating the river, leading to the loss of all fish life. While the leak was promptly repaired and the deceased fish removed, significant time will be required for the river's ecosystem to recover.",
            "desc-2": "A grounded oil tanker released a million barrels of crude oil along the coast, resulting in catastrophic losses to birdlife and  shutting down the local beach tourism industry for years to come. The incident has left residents and businesses deeply concerned about the region's long-term prospects.",
            "desc-3": "A local farm's use of a pesticide has decimated the local bee population that prevented pollination of local crops and plants, leading to significant commercial and environmental consequences.Some residents and businesses are moveing away to areas with improved quality of life.",
            "outcome-heading": "Resilience Challenge Outcomes",
            "outcome-0": "The municipality's decisions have made the town highly sensitive to environmental pollution, and there appears to be nothing in place for the residents of the town, making a bad situation much worse. People feel that the municipality has 'really dropped the ball' with their biodiversity resilience planning, and it's expected that the mayor will resign.",
            "outcome-1": "The event has caused substantial damage to our town's biodiversity - impacting the plants, animals, and local businesses that rely on a healthy ecosystem. Restoring this balance will require significant effort. While we are thankful the situation wasn't more severe, there is an understanding that some aspects of our approach to protecting natural resources could be strengthened.",
            "outcome-2": "The event had a minimal impact with no serious damage to the local ecosystem. This outcome underscores the importance of proactive measures to protect biodiversity and ensure long-term environmental sustainability. The municipality's commitment to these principles is clearly contributing to the health and resilience of our community.",
            "outcome-3": "The event seems to have had minimal effect on the town, bringing great comfort to everyone. However, some are questioning whether the municipality might have been overly cautious in their preparations, wondering if similar future challenges could also be managed so effortlessly.",
            "local_url": "kb/resilience/resilience_01.html",
            "url": "https://arsinoe-serious-game.github.io/kb/resilience/resilience_01.html",
            "qr_code": "assets/resilience/resilience_01_qr.png"
        },
        {
            "type": "FP",
            "name": "Flood Resilience Challenge",
            "heading-0": "What are flood resilience challenges?",
            "desc-0": "Flood resilience is challenged when water enters areas where it doesn't belong, often due to excessive rainfall, storm surges, or man-made flooding. Flooding can cause direct damage to properties, public safety and health, as well as indirect disruptions to services, business continuity, and the economy. <br> ",
            "heading-1": "Minor Resilience Challenge",
            "heading-2": "Average Resilience Challenge",
            "heading-3": "Extreme Resilience Challenge",
            "desc-1": "It's been raining more than expected for the time of year and the ground has become sodden, resulting in localised flooding. This impacts local people and businesses and takes resources to clean up once the flood water recedes.",
            "desc-2": "The town has been battered by multiple winter storms, with each storm causing flooding that the town is struggling to recover from before being hit by the next one. Residents and businesses are starting to get nervous about the future.",
            "desc-3": "The region has been absolutely battered by a once in a lifetime storm that has dumped unprecedented amounts of rain in the region, causing huge amount of damage. Rebuilding will take time and effort. <br> Some residents and businesses are now looking to move away to areas that have a better quality of life.",
            "outcome-heading": "Resilience Challenge Outcomes",
            "outcome-0": "The municipality's decisions have left the town vulnerable to flooding. When the recent flood occurred, residents found little support in place, exacerbating the difficulties. Many feel the municipality failed to adequately plan for flood resilience, and the mayor's resignation is anticipated. ",
            "outcome-1": "The flood has caused considerable damage, requiring significant effort to rebuild infrastructure and support affected communitites. Sadly, some businesses have closed and many residents face hardship. While the situation could have been more severe, there is a feeling that more could have been done in advance to prepare for this event.",
            "outcome-2": "While the flood has resulted in some minor impacts, fortunately there were no major injuries or loss of life. This is welcome news for local businesses and residents alike. The municipality's planning efforts appear to have been effective in mitigating the worst potential outcomes.",
            "outcome-3": "The flood impact on the town appears to be limited, which is reassuring for local businesses and residents. However, the relatively small effect has led some to question whether the level of preparation was proportionate to the potential risk, and whether this preparedness will translate into resilience when facing future challenges.",
            "local_url": "kb/resilience/resilience_02.html",
            "url": "https://arsinoe-serious-game.github.io/kb/resilience/resilience_02.html",
            "qr_code": "assets/resilience/resilience_02_qr.png"
        },
        {
            "type": "DP",
            "name": "Drought Resilience Challenge",
            "heading-0": "What are drought resilience challenges?",
            "desc-0": "Drought resilience is challenged when there isn't enough water to meet consumption needs. These droughts are usually caused by a lack of available water, due to consistently low rainfall or the overuse of surface and groundwater over time.",
            "heading-1": "Minor Resilience Challenge",
            "heading-2": "Average Resilience Challenge",
            "heading-3": "Extreme Resilience Challenge",
            "desc-1": "The town has a drier winter than expected, resulting in the main supply reservoirs being low, and a dry spring. By summer, the water board is restricting water use to essential activities only.",
            "desc-2": "The town has seen less rain than usual over the past year. We hoped last year's low rainfall was just a temporary dip, but unfortunately, that pattern is continuing now. Residents and businesses are understandably concerned about what this means for the future.",
            "desc-3": "The town is facing challenges due to changing climate patterns that have significantly reduced rainfall, resulting in a drier landscape and limited water resources. While this presents difficulties for the community. Residents and businesses are considering relocation to areas with a more resilient environment.",
            "outcome-heading": "Resilience Challenge Outcomes",
            "outcome-0": "The municipality's past decisions have increased the town's vulnerability to water resources fluctuations. With diminishing water reserves and lacking adequate solutions, the challenging circumstances are intensifying. There is growing criticism of the municipality for not adequately preparing for a drought, raising speculation about whether the mayor may resign soon.",
            "outcome-1": "The drought has seriously  affected the town, resulting in extensive work needed to recover services. This situation has led to business closures and numerous residents facing hardships. Despite the conditions could have been worse, many believe the response might have been much improved if not for perceived shortcomings. Residents feel that the municipaltity mishandled its drought planning efforts.",
            "outcome-2": "The drought had only minor effects on the town. This outcome brings considerable comfort to both local businesses and residents. Many believe that the municipality have successfully handled their drought preparations.",
            "outcome-3": "The recent event seems to have had minimal effect on the town, providing a huge relief for both local businesses and residents. However, some question whether the municipality may have been overly cautious in their preparations, leading them to wonder if similar future challenges could also be managed so effortlessly.",
            "local_url": "kb/resilience/resilience_03.html",
            "url": "https://arsinoe-serious-game.github.io/kb/resilience/resilience_03.html",
            "qr_code": "assets/resilience/resilience_03_qr.png"
        },
        {
            "type": "HP",
            "name": "Heat Resilience Challenge",
            "heading-0": "What are heat resilience challenges?",
            "desc-0": "Heat resilience challenges occur during prolonged periods of excessive local heat, characterized by consecutive days of unusually high temperatures. Heat waves exacerbate numerous risks, including health-related concerns, increased human mortality, economic impacts,  drought, water quality degradation, wildfire risk, power shortages, and agricultural losses.",
            "heading-1": "Minor Resilience Challenge",
            "heading-2": "Average Resilience Challenge",
            "heading-3": "Extreme Resilience Challenge",
            "desc-1": "The town normally has great summers, but this summer was a lot hotter than normal, making it hard to enjoy the weather as it was just too hot. ",
            "desc-2": "The town's hot summer has now extended into a hot autumn and a hot winter. Whilst tourists are enjoying the winter sun, residents have had their fill. Residents and businesses are starting to get nervous about the future.",
            "desc-3": "The town appears to be in a climate change where it's just so hot all the time, resulting in the landscape becoming drier and browner.  Residents and businesses are now looking to move away to areas that are less harsh and have a better quality of life.",
            "outcome-heading": "Resilience Challenge Outcomes",
            "outcome-0": "The municipality's decisions have left the town highly vulnerable to intense heatwaves.  As record-high temperatures strain daily life, lacking preparedness measures exacerbates the suffering of residents. Public strongly criticizes the perceived failures in the municipality's heatwave strategy, leading to a widespread expectation that the mayor will step down due to this oversight. ",
            "outcome-1": "The town is experiencing difficulties following the recent event, requiring significant infrastructure repairs and resulting in some business closures and hardships for residents. While acknowledging the situation could be graver, many feel outcomes could have been lessen had the municipality handled things differently. There's a prevailing critic that local leadership mishandled their response to the event. ",
            "outcome-2": "The town experiences only minor effects from the heatwave, with no significant incidents or casualties reported. This outcome is a huge relief for both local businesses and residents. People think that the municipality have managed the heat wave situation adequately.",
            "outcome-3": "Despite its passage with little noticeable impact, the recent heatwave brought a collective sense of relief to the town's residents and businesses. Nonetheless,  some are wondering if the municipality's extensive preparedness measures were perhaps excessive, and questioning its capacity for coping with similar events in the future. ",
            "local_url": "kb/resilience/resilience_04.html",
            "url": "https://arsinoe-serious-game.github.io/kb/resilience/resilience_04.html",
            "qr_code": "assets/resilience/resilience_04_qr.png"
        }
    ],
    "text": [
        {
            "ID": "MAYOR_DETAIL",
            "text": "Welcome to the mayoral office. <br>  <br> Your role is to lead your team of citizens to ensure that they come to their decisions quickly and efficiently, while exploring the options in enough depth to make reasoned decisions.  <br>  <br> The reward for success is knowing that you have lead your citizens to make difficult decisions for the good of the town. <br>  <br>  <b> However, the price of failure is high. <b> "
        },
        {
            "ID": "H2020_HEADER",
            "text": "This project has received funding from the European Union's Horizon H2020 innovation action programme under grant agreement 101037424. "
        }
    ],
    "interventions": [
        {
            "type": "BP",
            "name": "Approve a <br> fish farm",
            "desc": "An offshore fish farm that optimizes fish yields using modern aquaculture techniques has been proposed, which will create local jobs in both fish cultivation and processing, and offer more high-quality fish at both regional and national levels. <br>  <br> However, fish farms are criticised for promoting monocultures, not only among farmed fish species but also by impacting the biodiversity in the surrounding waters. Additionally, lacking of transparency in some fish farming operations, particularly regarding their husbandry practices, raises concerns.",
            "case_study": "",
            "EP": "4",
            "BP": "-1",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-heading": "Fish farm <br> Outcomes",
            "outcome-0": "The farm's operations have heavily polluted the water, endangering marine life through the release of pathogens and parasites.",
            "outcome-1": "The fish farm is attracting sharks, resulting in an attack on a local surfer. ",
            "outcome-2": "The fish farms are operational and working well, creating jobs and adding fish to the local palette. ",
            "outcome-3": "The fish farming has been a great success! Many more people can afford to have locally supplied fresh fish, saving air miles. The income from the farming has been put back into the local community in educating local fishermen on sustainable fishing practice",
            "img": "fish_farm.jpg",
            "local_url": "kb/interventions/interventions_0.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_0.html",
            "qr_code": "assets/interventions/interventions_0_qr.png"
        },
        {
            "type": "BP",
            "name": "Approve a <br> monofarm",
            "desc": "A large-scale commercial farm on currently unused farmland has been proposed that utilizes modern agricultural techniques to maximize crop production, focusing on high-yield, disease-resistant varieties. The farm is expected to generate local employment and contribute to regional food supply. <br>  <br> However, the planned use of intensive pesticides and high water consumption raises concerns about potential negative impacts on local biodiversity and water resources. These environmental risks will need to be carefully assessed and managed.",
            "case_study": "",
            "EP": "4",
            "BP": "-1",
            "FP": "-1",
            "DP": "-1",
            "HP": "0",
            "outcome-heading": "Monofarm <br> Outcomes",
            "outcome-0": "The selected crop has proven highly invasive, spreading to other farms and people's gardens. It is outcompeting native plants and decreasing local biodiversity.",
            "outcome-1": "The farm is producing bumper crop yields, but requires considerably more water than anticipated,  resulting in the local water company suggesting that people only shower once a week to save water.",
            "outcome-2": "The farm is producing an expected return and has created local jobs. The farm operators are careful to consider local biodiversity issues.",
            "outcome-3": "The farm is producing bumper crop yields and is managing to deliver them in harmony with the environment. To conserve water, the farm has developed a sophisticated irrigation system that has gained wide praise.",
            "img": "monofarm.jpg",
            "local_url": "kb/interventions/interventions_01.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_01.html",
            "qr_code": "assets/interventions/interventions_01_qr.png"
        },
        {
            "type": "BP",
            "name": "Citizen <br> biodiversity",
            "desc": "A citizen science project aimed at engaging members of the public in observing and recording local flora and fauna using a mobile app has been proposed. <br>  <br> By documenting environmental observations, the project will assist researchers in assessing the current state of local ecosystems and tracking changes over time, helping identify both positive and negative trends in biodiversity.",
            "case_study": "CS9",
            "EP": "0",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-heading": "Citizen biodiversity <br> Outcomes",
            "outcome-0": "The project is a disaster! The app is developed by a consultancy with little understanding or interest in the project and product a buggy mess that nobody wants.",
            "outcome-1": "Theres's a small, but hardcore set of citizen users recording everything they can. This provides researchers with useful insights, but the project really needs more scale.",
            "outcome-2": "The project is a success, with the app being popular for school projects and wildlife enthusiasts. The app is niche, but provides a lot of value.",
            "outcome-3": "The project is a great success, with residents keen to monitor the wildlife they see around them. The app's data provides local biodiversity researchers with clear insights into the state of the environment allowing for meaningful interventions.",
            "img": "dashboard.jpg",
            "local_url": "kb/interventions/interventions_02.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_02.html",
            "qr_code": "assets/interventions/interventions_02_qr.png"
        },
        {
            "type": "BP",
            "name": "Protect <br> local biodiversity",
            "desc": "A proposal to create wildlife park dedicated to the protection and conservation of local flora and fauna has been submitted. <br>  <br> The park plans to establish a breeding program for rare and threatened animal species, with the goal of reintroducing them into the surrounding environment to help maintain healthy and sustainable populations.",
            "case_study": "CS9",
            "EP": "1",
            "BP": "3",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-heading": "Protect local <br> biodiversity Outcomes",
            "outcome-0": "The project is a disaster! An initial breeding programme to strengthen the wolf community led to wolves growing out of control and decimated local pets.",
            "outcome-1": "Whilst the wildlife park has been able to breed endangered local animals, returning  them to their environments always proved difficult, leading to accusations that the park staff were incompetent. ",
            "outcome-2": "The project is a success, with the wildlife park receiving awards for its programmes. There's interest from the community, but it's felt that people would rather enjoy their days out.",
            "outcome-3": "The project is a great success, with the success reintroduction of rare species. The park is popular with both locals and tourists, offering both the opportunity to see rare animals and to learn about conservation.",
            "img": "protect_biodiversity.jpg",
            "local_url": "kb/interventions/interventions_03.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_03.html",
            "qr_code": "assets/interventions/interventions_03_qr.png"
        },
        {
            "type": "BP",
            "name": "Legally protect <br> local crops",
            "desc": "A local farming group is seeking legal protection for their regionally produced crops under relevant EU legislation (Geographical Indication or GI tagging of crops). This designation would ensure that only crops grown in this specific area can use the region's name, preventing producers in other regions from marketing similar products under the same label.",
            "case_study": "CS9",
            "EP": "2",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-heading": "Legally protect local crops Outcomes",
            "outcome-0": "The project is a disaster! The lawyers engaged didn't understand trademarking and lost their case, severely undermining the financial security of the farmers.",
            "outcome-1": "The project is a limited success. Whilst the crop has been protected, companies in other regions have been quick to relabel their ingredients and food products with new names. For many consumers, the difference are neither here nor there.",
            "outcome-2": "The project is a success, with crop protection in place, the farmers can operate securely knowing that their crop comes from this town.",
            "outcome-3": "The project is a great success, with the local crop being protected, farmers have built a popular heritage industry around their crop and the foodstuffs that can be made from it. ",
            "img": "protect_local_crops.jpg",
            "local_url": "kb/interventions/interventions_04.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_04.html",
            "qr_code": "assets/interventions/interventions_04_qr.png"
        },
        {
            "type": "BP",
            "name": "Create a biodiversity <br> knowledge base",
            "desc": "A community website designed to provide residents with practical information and resources to promote local biodiversity is requesting for municipality's support. <br>  <br> Research indicates that poor biodiversity decisions often stem from limited knowledge and guidance. The website aims to empower residents, by offering useful knowledge, to make informed choices that support and enhance the local environment.",
            "case_study": "CS9",
            "EP": "-1",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-heading": "Biodiversity knowledge base Outcomes",
            "outcome-0": "The project starts with a lot of fanfare, but the work is passed off to a low-cost bureau who have issues and produce a strange website that serves no-one.",
            "outcome-1": "The project is well-managed with a suitable design bureau delivering a great website. However, the ball is dropped when it comes to advertising  the site, with few residents event being aware that the site event exists. ",
            "outcome-2": "The project is delivered and residents are aware and using the website. After an expected biodiversity event, many residents cite the website as being a great resource for helping to deal with  issues.",
            "outcome-3": "The project is a great success with residents regularly engaging and contributing with the website, to the point that it has become nationally recognised with other towns starting to adopt a similar approach. ",
            "img": "dashboard.jpg",
            "local_url": "kb/interventions/interventions_05.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_05.html",
            "qr_code": "assets/interventions/interventions_05_qr.png"
        },
        {
            "type": "BP",
            "name": "Create a biodiversity <br> digital twin ",
            "desc": "The municipality plans to develop a biodiversity modelling digital twin to monitor local biodiversity and assess the potential negative impacts of different human activities that could affect the ecosystem resilience. <br>  <br> This digital twin will integrate real-world data with simulation models to generate actionable insights. Its effectiveness will largely depend on the quality of the data collected and the accuracy of the underlying models.",
            "case_study": "",
            "EP": "-1",
            "BP": "3",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-heading": "Biodiversity digital twin Outcomes",
            "outcome-0": "The project is handed off to a consultancy group who appear to have strange views about what constitutes appropriate biodiversity data and models, resulting in a useless tool.",
            "outcome-1": "The digital twin generally works, but its AI seems to produce a lot of nightmare fuel, often predicting extinction events. This makes it hard to trust the twin's outputs. ",
            "outcome-2": "The digital twin works well and is providing some good biodiversity strategy insights. The municipality is happy and would like to develop it further.",
            "outcome-3": "The digital twin is providing the municipality with great insights and predictions, allowing biodiversity protection activities to be far better targeted. Most residents don't notice, but biodiversity resilience is growing year on year.",
            "img": "digital_twin.jpg",
            "local_url": "kb/interventions/interventions_06.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_06.html",
            "qr_code": "assets/interventions/interventions_06_qr.png"
        },
        {
            "type": "DP",
            "name": "Approve reservoir <br> construction ",
            "desc": "A local water company proposes to construct a large reservoir in a nearby valley. The reservoir would capture runoffs during the wet seasons, helping establish a more reliable year-round water supply and alleviate water scarcity during the dry seasons. <br>  <br> However, flooding the valley would significantly alter local ecosystem, displacing wildlife and disrupting fish migration along the river affected by the reservoir.",
            "case_study": "",
            "EP": "-2",
            "BP": "-1",
            "FP": "2",
            "DP": "3",
            "HP": "0",
            "outcome-heading": "Reservoir construction Outcomes",
            "outcome-0": "The project is a disaster! The dam has been successfully constructed, but it's empty! It turns out that the municipality signed the wrong water ordinances and the expected inflowing rives are flowing elsewhere.",
            "outcome-1": "Reduced flows downstream have affected local fish population. The local angling community are unhappy ",
            "outcome-2": "There was a serve drought in the summer. Luckily because of the reservoir there is enough water for the township. ",
            "outcome-3": "There was a serve drought in the summer. However, with the winter rains captured in the reservoir, there is easily enough water for all.",
            "img": "reservoir.jpg",
            "local_url": "kb/interventions/interventions_07.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_07.html",
            "qr_code": "assets/interventions/interventions_07_qr.png"
        },
        {
            "type": "DP",
            "name": "Approve a golf resort <br> development",
            "desc": "A leading resort developer proposes to build a golf course resort on currently unused land. The project aims to attract affluent golf enthusiasts and is expected to stimulate  local economy by creating jobs and generating commercial opportunities for residents. <br>  <br> However, concerns have been raised about the resort's high water demands to maintain the course, as well as the possibility that much of the generated wealth may remain within the resort's gated community, limiting broader economic benefits to the surrounding area.",
            "case_study": "",
            "EP": "5",
            "BP": "-1",
            "FP": "0",
            "DP": "-1",
            "HP": "0",
            "outcome-heading": "golf resort development Outcomes",
            "outcome-0": "The project is a disaster! Whilst the course was constructed with no issues, running the resort requires a vast amount of water, with the water company suggesting that people only shower once a week to save water. ",
            "outcome-1": "The high resort fees tend to greatly limit the number of guests at any time and most just come to play golf and move on. There's not a lot of trickle down to the town, and if you didn't know the course was there, you probably wouldn't know about it.",
            "outcome-2": "The course is a success, though the high resort fees tend to keep the resort ticking over, giving a relaxed feel. The course has been good for the town, with jobs to support the course and the customers.",
            "outcome-3": "Golf tourists come from far and wide to play, and when they aren't playing a lot of them are visiting the town and spending money on good days and nights out.",
            "img": "golf_course.jpg",
            "local_url": "kb/interventions/interventions_08.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_08.html",
            "qr_code": "assets/interventions/interventions_08_qr.png"
        },
        {
            "type": "DP",
            "name": "Approve water <br> delivery service",
            "desc": "The municipality is considering importing bottled water from abroad to address drinking water shortages during drought conditions. This approach would provide a reliable summer water supply and is significantly less expensive in the short term than upgrading the town's aging water distribution infrastructure. <br>  <br> However, regular deliveries of bottled water could contribute to traffic congestion and raise public concerns. There is also a reputational risk that the municipality may be seen as avoiding long-term solutions in favor of quick, externally sourced fixes. <br> ",
            "case_study": "",
            "EP": "-2",
            "BP": "0",
            "FP": "0",
            "DP": "2",
            "HP": "1",
            "outcome-heading": "Water delivery service Outcomes",
            "outcome-0": "It's a disaster,  the water did not pass quality assurance and can not be consumed.  Instead the costly water is just being used for non-human use. ",
            "outcome-1": "The effects of a hot and dry summer have been offset through the water. While not a perfect solution, it has had a positive effect.",
            "outcome-2": "Despite a hot and dry summer, there are adequate water reserves and tourism benefits.",
            "outcome-3": "Despite a very hot and dry summer, there's more than enough water bringing in lots of tourists from other drier areas. ",
            "img": "water_delivery_service.jpg",
            "local_url": "kb/interventions/interventions_09.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_09.html",
            "qr_code": "assets/interventions/interventions_09_qr.png"
        },
        {
            "type": "DP",
            "name": "Install smart <br> water meters",
            "desc": "The municipality plans to install smart domestic water meters that enable residents to monitor their  water usage in real-time and detect potential leaks within their homes. Users can see their  minute-by-minute consumption such as showering, garden irrigation, dishwashing and clothes washing. <br>  <br> While this technology offers valuable insights, user engagement tends to decline over time as the initial novelty of monitoring water usage diminishes.",
            "case_study": "",
            "EP": "2",
            "BP": "0",
            "FP": "1",
            "DP": "2",
            "HP": "1",
            "outcome-heading": "smart water meter Outcomes",
            "outcome-0": "The project is a disaster! The municipality advocated for the smart meter app, but it turned to be full of spyware, collecting customer details and making unauthorised charges on customer accounts.",
            "outcome-1": "Meters have been installed, but the public response is apathetic. There is a perception that the meters are part of a 'surveillance society' that will use water consumption data to clamp down on civil liberties.",
            "outcome-2": "The smart water meters have been accepted by residents and water consumption is starting to show a reduction as enthusiastic residents look to minimise consumption.",
            "outcome-3": "Residents love the app and consumption is at an all-time low. This allows the water company to spend more time and resources addressing leakage.",
            "img": "smart_meters.jpg",
            "local_url": "kb/interventions/interventions_10.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_10.html",
            "qr_code": "assets/interventions/interventions_10_qr.png"
        },
        {
            "type": "DP",
            "name": "Precision irrigation <br> system",
            "desc": "The municipality is seeking to collaborate with local market gardeners to implement precision irrigation systems aimed at reducing water consumption. <br>  <br> The town hosts a significant market gardening industry that places substantial demand on tap water. Farmers often on the side of overwatering, despite the potential negative impact on crop health. By using computer-assisted systems to assess the actual water needs of crops, irrigation can be optimized, leading to lower overall water use and enabling the cultivation of currently marginal land.",
            "case_study": "",
            "EP": "2",
            "BP": "0",
            "FP": "1",
            "DP": "2",
            "HP": "0",
            "outcome-heading": "Smart irrigation programme Outcomes",
            "outcome-0": "The project is a disaster! The smart irrigation platform is very buggy and is over-watering to the point of causing local flooding.",
            "outcome-1": "Smart irrigation systems have been installed, with mixed results. Some farmers are reporting success, but many are reluctant to use them as they feel that they have a much better understanding of crop requirements.",
            "outcome-2": "The smart irrigation system seem to be working alright, though there have been a few teething issues. Most farmers are reporting that the system is working well for them, though a few have run into issues.",
            "outcome-3": "The smart irrigation systems are working well, with most farmers reporting both significant reductions in water requirements but also increases in yield. In some cases, marginal land is being returned to use.",
            "img": "smart_irrigation.jpg",
            "local_url": "kb/interventions/interventions_11.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_11.html",
            "qr_code": "assets/interventions/interventions_11_qr.png"
        },
        {
            "type": "DP",
            "name": "Create a drought dashboard",
            "desc": "The municipality plans to develop a community website that will provide residents with practical information and support to help them navigate drought events. <br>  <br> Research indicates that residents often experience greater stress from the anticipation of a drought than from the actual event itself. By offering clear, accessible resources, the website can help alleviate concerns, increase awareness, and empower the community with the knowledge needed to respond effectively.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "0",
            "DP": "2",
            "HP": "0",
            "outcome-heading": "Drought dashboard Outcomes",
            "outcome-0": "The project starts with a lot of fanfare, but the work is passed off to a low-cost bureau who have issues and produce a strange website that serves no-one.",
            "outcome-1": "The project is well-managed with a suitable design bureau delivering a great website. However, the site isn't advertised well, with few residents event being aware that the site event exists. ",
            "outcome-2": "The project is delivered and residents are aware and using the website. After an unseasonal flood, many residents cite the website as being a great resource for helping them to come to terms with flooding issues.",
            "outcome-3": "The project is a great success with residents regularly engaging and contributing with the website, to the point that it has become nationally recognised with other towns starting to adopt a similar approach. ",
            "img": "dashboard.jpg",
            "local_url": "kb/interventions/interventions_12.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_12.html",
            "qr_code": "assets/interventions/interventions_12_qr.png"
        },
        {
            "type": "DP",
            "name": "Create a drought <br> digital twin",
            "desc": "The municipality will develop a drought modelling digital twin to assess the likelihood and potential impacts of future drought events. This tool will support improved preparedness and inform long-term planning for drought resilience. <br>  <br> By integrating live data with advanced simulation models, the digital twin will generate valuable insights. Its effectiveness, however, will depend heavily on the quality of the data collected and the accuracy of the underlying models.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "0",
            "DP": "3",
            "HP": "0",
            "outcome-heading": "Drought digital twin Outcomes",
            "outcome-0": "The project is handed off to a consultancy group who appear to have strange views about what constitutes appropriate drought data and models, resulting in a useless tool.",
            "outcome-1": "The digital twin generally works, but its AI seems to produce a lot of nightmare fuel, often predicting droughts during rain storms. This makes it hard to trust the twin's outputs. ",
            "outcome-2": "The digital twin works well and is providing some good insights, not least a model for forecasting water scarcity. The municipality is happy and would like to develop it further.",
            "outcome-3": "The digital twin is providing the municipality with great insights and predictions, allowing conservative water consumption activities to be far better targeted. Most residents don't notice, but the impact of droughts is decreasing year by year.",
            "img": "digital_twin.jpg",
            "local_url": "kb/interventions/interventions_13.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_13.html",
            "qr_code": "assets/interventions/interventions_13_qr.png"
        },
        {
            "type": "FP",
            "name": "Approve sea wall <br> construction",
            "desc": "The community along the coastal road has been repeatedly impacted by sea flooding, driven by high tides and onshore winds, causing significant disruption of services, costly property damage and extensive clean-up efforts. <br>  <br> Despite the wall cannot fully elimiate the risks of extreme events and could affect the scenic coastal, views, and the construction process will be disruptive, the long-term benefits, including improved safety, reduced damage, and economic stability, may outweigh the drawbacks, supporting the community's growth and resilience.   <br> ",
            "case_study": "",
            "EP": "2",
            "BP": "0",
            "FP": "2",
            "DP": "0",
            "HP": "0",
            "outcome-heading": "Sea wall construction Outcomes",
            "outcome-0": "The project is a legal disaster area! Residents of nearby 'Cliff Heights' raise long and costly  objections as their district is being allowed to erode into the sea, resulting in the project being substantially delayed. ",
            "outcome-1": "The project completes on time and is warmly received despite ruining the view of the bay from the, now protected, coast road.\u200b",
            "outcome-2": "The project completes slightly ahead of time, early enough to protect the coastal road from some unseasonally high tides.",
            "outcome-3": "Shortly after the project completes, the town is buffeted a number of huge storms, the worst in living memory. Unlike previous storms, the coast road district doesn't flood saving the council by not having to perform a large clean-up. ",
            "img": "sea_wall.jpg",
            "local_url": "kb/interventions/interventions_14.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_14.html",
            "qr_code": "assets/interventions/interventions_14_qr.png"
        },
        {
            "type": "FP",
            "name": "Approve out-of-town <br> leisure resort",
            "desc": "A retail company proposes to develop a large out-of-town retail and leisure park on currently unused land, which brings long-term employment opportunities to the area and attract a significant number of visitors to the town.  <br>  <br> However, there are concerns that the development could negatively impact the town centre, as shoppers may prefer the convenience of the new retail hub. Additionally, the proposed site is a well-loved local meadow, valued by the community for recreation and green space.",
            "case_study": "",
            "EP": "4",
            "BP": "-1",
            "FP": "-1",
            "DP": "0",
            "HP": "-1",
            "outcome-heading": "Out-of-town leisure resort Outcomes",
            "outcome-0": "The complex is a titanic success, so much so that there's gridlock in and around the town as everybody wants to go there making it impossible to travel anywhere.",
            "outcome-1": "The complex is a success, but heavy rains frequently flood the huge car parks and cause major traffic jams. ",
            "outcome-2": "The complex is a success with tenants that complement rather than compete with the town centre attractions. ",
            "outcome-3": "The complex is a real success and careful transport planning has enabled people from all over the region to attend films, gigs, and shows without causing chaos. ",
            "img": "lesiure_resort.jpg",
            "local_url": "kb/interventions/interventions_15.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_15.html",
            "qr_code": "assets/interventions/interventions_15_qr.png"
        },
        {
            "type": "FP",
            "name": "Approve nature-based <br> flood protection",
            "desc": "The local university suggests to host a beaver-led land management project as a nature-based solution aimed at reducing river flooding. The low-cost project positions the municipality as forward-thinking in its approach to climate resilience and environmental sustainability, which could generate valuable insights into natural flood mitigation. <br>  <br> However, the beavers may dig burrows and channels that affect the stability of river banks, leading to erosions, damage to crops and property.",
            "case_study": "",
            "EP": "0",
            "BP": "3",
            "FP": "2",
            "DP": "1",
            "HP": "0",
            "outcome-heading": "Nature-based flood protection Outcomes",
            "outcome-0": "The research is a disaster! The beavers have moved to the local arboretum and destroyed most of the rare saplings. The university abandoned the research as unworkable.",
            "outcome-1": "The beaver area suffers from a heavy rainstorm  resulting in beaver damn bursts and flooding in the downstream ",
            "outcome-2": "The beaver experiment is working well, and the university is working to increase size of the project, protecting more land. ",
            "outcome-3": "The beaver experiment is working well, with fewer floods. The beavers have been a local point of interest , drawing in beaver tourists and the sale of beaver plushies is through the roof. ",
            "img": "beavers.jpg",
            "local_url": "kb/interventions/interventions_16.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_16.html",
            "qr_code": "assets/interventions/interventions_16_qr.png"
        },
        {
            "type": "FP",
            "name": "Return seaside golf <br> course to sea",
            "desc": "The town's seaside golf course is increasingly threatened by rising sea levels and high tides due to global warming despite the municipality has spent huge budget to protect it from natural encroachment. Allowing the course to return to the sea would enable the municipality allocating its limited budget more effectively, support the creation of a wildlife wetland, and reduce traffic along the shoreline. <br>  <br> However, this decision may upset the golfers who regularly use the course and may be perceived by some residents as the municipality abandoning parts of the town to nature.",
            "case_study": "",
            "EP": "0",
            "BP": "2",
            "FP": "2",
            "DP": "1",
            "HP": "0",
            "outcome-heading": "Return seaside golf course to sea Outcomes",
            "outcome-0": "As the golf course returns to nature, the town is hit by a 'once in a generation' storm with extreme tides that rush over the course and undermine the mainline rail track, causing it to be out of use for six months.",
            "outcome-1": "The course is returned to nature, but local golfers protest the decision by playing 'urban golf' in the town centre. ",
            "outcome-2": "As the course returns to wetland, it becomes a popular destination for firstly, birds and then bird watchers.",
            "outcome-3": "Hearing the news,  a former champion golfer buys the old typewriter factory and rejuvenates it into a high-quality course that keen golfers flock to, boosting tourism substantially. ",
            "img": "golf_course.jpg",
            "local_url": "kb/interventions/interventions_17.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_17.html",
            "qr_code": "assets/interventions/interventions_17_qr.png"
        },
        {
            "type": "FP",
            "name": "Engage in flood plain <br> management",
            "desc": "The municipality will develop a floodplain management plan for the local river to reduce floodings in downstream neighbourhoods. The project will remove existing developments and allowing the land to naturally flood and store excess water, it can also support new recreational opportunities and attract diverse wildlife. <br>  <br> However, it is important to communicate clearly with stakeholders that floodplain management will not completely eliminate flooding, as misunderstandings could lead to concerns or opposition.",
            "case_study": "",
            "EP": "-1",
            "BP": "2",
            "FP": "2",
            "DP": "1",
            "HP": "0",
            "outcome-heading": "Flood plain management Outcomes",
            "outcome-0": "The project is a disaster! There was a major flood , and a much larger area of land was flooded. Farming land has been destroyed and polluted waters flow through the town. ",
            "outcome-1": "The project appears to have been a success but key stakeholders seem unhappy with the outcomes and are currently blaming each other for any issues that arise.",
            "outcome-2": "The project appears to have been a success and stakeholders appear happy with the outcome. There appears to be less flooding after recent heavy storms and evidence of increased biodiversity .",
            "outcome-3": "The project was a great success. A rare species of butterfly has been seen in the area and bird species have increased. The downstream town also did not suffer flooding in the last heavy rainfall event",
            "img": "flood_plain.jpg",
            "local_url": "kb/interventions/interventions_18.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_18.html",
            "qr_code": "assets/interventions/interventions_18_qr.png"
        },
        {
            "type": "FP",
            "name": "Create a <br> flood support website ",
            "desc": "The municipality plans to create a community website that offers residents practical information and signposts resources to prepare for floods.  <br>  <br> Research shows that an easy access knowledge hub helps citizens getting knowledge and practical advices for flood preparation, receiving live updates and taking early actions to mitigate flood impacts, and finding support during crisis.  <br> ",
            "case_study": "CS6",
            "EP": "-1",
            "BP": "0",
            "FP": "2",
            "DP": "0",
            "HP": "0",
            "outcome-heading": "Flood support website Outcomes",
            "outcome-0": "The project starts with a lot of fanfare, but the work is passed off to a low-cost bureau who have issues and produce a strange website that serves no-one.",
            "outcome-1": "The project is well-managed with a suitable design bureau delivering a great website. However, the ball is dropped when it comes to advertising  the site, with few residents event being aware that the site event exists. ",
            "outcome-2": "The project is delivered and residents are aware and using the website. After an unseasonal flood, many residents cite the website as being a great resource for helping them to come to terms with flooding issues.",
            "outcome-3": "The project is a great success with residents regularly engaging and contributing with the website, to the point that it has become nationally recognised with other towns starting to adopt a similar approach. ",
            "img": "dashboard.jpg",
            "local_url": "kb/interventions/interventions_19.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_19.html",
            "qr_code": "assets/interventions/interventions_19_qr.png"
        },
        {
            "type": "FP",
            "name": "Create a flooding <br> digital twin",
            "desc": "The municipality will develop a flood modelling digital twin topredict flooding and evaulate possible emergency response measures to support flood crisis management. <br>  <br> By integrating real-world data with advanced simulation models, the digital twin will generate valuable insights. Its effectiveness will depend largely on the quality of the data collected and the accuracy of the modelling.",
            "case_study": "CS8",
            "EP": "-1",
            "BP": "0",
            "FP": "3",
            "DP": "0",
            "HP": "0",
            "outcome-heading": "Flooding digital twin Outcomes",
            "outcome-0": "The project is handed off to a consultancy group who appear to have strange views about what constitutes appropriate flood data and models, resulting in a useless tool.",
            "outcome-1": "The digital twin generally works, but its AI seems to produce a lot of nightmare fuel, often predicting impossible tsunamis on the coast. This makes it hard to trust the twin's outputs. ",
            "outcome-2": "The digital twin works well and is providing some good insights, not least a predictive flood model for coastal road closures. The municipality is happy and would like to develop it further.",
            "outcome-3": "The digital twin is providing the municipality with great insights and predictions, allowing flood protection activities to be far better targeted. Most residents don't notice, but the impact of flooding is decreasing yearly.",
            "img": "digital_twin.jpg",
            "local_url": "kb/interventions/interventions_20.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_20.html",
            "qr_code": "assets/interventions/interventions_20_qr.png"
        },
        {
            "type": "HP",
            "name": "Approve installation of  <br> cool roofs",
            "desc": "Plans have been submitted to apply reflective paint to roofs, aiming to reduce indoor temperatures and mitigate heat in the surrounding environment. <br>  <br> This approach is generally a low-cost and non-invasive method for combating urban heat. However, its benefits are most significant in areas experiencing prolonged hot weather, and it may be counterproductive in locations where solar panels are installed.",
            "case_study": "CS1",
            "EP": "1",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "3",
            "outcome-heading": "Cool roofs <br> Outcomes",
            "outcome-0": "The project is a disaster! The painters have ended up painting everything and damaging many roof-top solar panels.",
            "outcome-1": "The roof painting phase of the project has been completed, but the expected heat wave is noticeable by its absence. The townspeople reckon the municipality is just wasting money on vanity projects.",
            "outcome-2": "The roofs have been painted just in time for the summer heat wave and are having the desired effect. Rooms in painted houses feel cooler and the surrounding streets are far more pleasant to be in.",
            "outcome-3": "The roofs have been painted and there's a record breaking heatwave in the region. Unlike last year, it feels cooler in the streets, even though the weather is warmer. Residents are relived and thankful that their summers are liveable again.",
            "img": "cool_roofs.jpg",
            "local_url": "kb/interventions/interventions_21.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_21.html",
            "qr_code": "assets/interventions/interventions_21_qr.png"
        },
        {
            "type": "HP",
            "name": "Approve installation of <br> firebreaks",
            "desc": "Plans have been submitted to install fire breaks in the dry hinterland to help reduce the long-term damage caused by heat-induced forest and scrub fires. These fire breaks will contain fires and prevent them from spreading, which would reduce pressure on emergency services and help limit biodiversity loss over time. <br>  <br> However, there are costs associated with both the installation and ongoing maintenance of the fire breaks. Additionally, the initial clearing of trees and scrubland may have short-term negative impacts on local biodiversity.",
            "case_study": "",
            "EP": "1",
            "BP": "1",
            "FP": "0",
            "DP": "1",
            "HP": "2",
            "outcome-heading": "Install firebreaks Outcomes",
            "outcome-0": "The fire breaks have been a massive failure after a scrubland fire overcame the breaks and raged out of control until it burnt itself out.",
            "outcome-1": "The fire breaks are a success, but there is a lot of backlash from locals and tourists that the breaks have ruined the natural beaty of the hinterland.",
            "outcome-2": "High winds and a prolonged drought have hit the area, leading to wild fires breaking out across the region. However, the breaks are able to contain the fire to relatively small regions,  greatly reducing damage. ",
            "outcome-3": "The fire breaks have proved to be very capable in limiting the spread of wildfire. However, they've had the added bonus of becoming popular tourist hiking routes.",
            "img": "firebreaks.jpeg",
            "local_url": "kb/interventions/interventions_22.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_22.html",
            "qr_code": "assets/interventions/interventions_22_qr.png"
        },
        {
            "type": "HP",
            "name": "Approve installation of <br> green walls",
            "desc": "The municipality plans to install green walls on buildings throughout the town to reduce local temperatures by cooling both the buildings and surrounding streets, encouraging greater daytime use of public spaces and increased foot traffic to local shops. <br>  <br> However, green walls require a consistent water supply to keep them green. Without proper maintenance, the plants may die, creating both biological and fire hazards.",
            "case_study": "CS1",
            "EP": "1",
            "BP": "1",
            "FP": "1",
            "DP": "1",
            "HP": "2",
            "outcome-heading": "Install green walls Outcomes",
            "outcome-0": "The green walls have not been adequately maintained. Clogged drainage systems have led to sewage overflows, making the buildings unpleasant to be around.",
            "outcome-1": "The green walls have been retrofitted and there has been no major setbacks. However, there has been an infestation of  aphids and spiders in one of the buildings which requires additional pest control.",
            "outcome-2": "The project was a success, many people have commented on the reduction of noise and stress within the workplace. ",
            "outcome-3": "The project was a great success. A local study has found that urban temperatures and air pollution have reduced, and less money has been spent on heating the buildings. ",
            "img": "green_walls.jpg",
            "local_url": "kb/interventions/interventions_23.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_23.html",
            "qr_code": "assets/interventions/interventions_23_qr.png"
        },
        {
            "type": "HP",
            "name": "Construct a <br> Miyawaki Forest",
            "desc": "The municipality plans to install small, densely planted, fast-growing forests in urban areas. Roughly the size of a tennis court, these compact forests can be established in a variety of locations and offer many of the benefits of larger woodlands, helping reduce urban heat, support biodiversity, and strengthen residents' connection with nature. <br>  <br> However, the focus on rapid growth may lead to the selection of tree species that are more vulnerable to pests and disease, potentially affecting the long-term health and resilience of these green spaces.",
            "case_study": "CS1",
            "EP": "0",
            "BP": "2",
            "FP": "1",
            "DP": "0",
            "HP": "1",
            "outcome-heading": "Miyawaki Forest Outcomes",
            "outcome-0": "Although fast growing, the tree species selected for the forest were susceptible to a local pest, resulting in many of the trees dying and becoming fire risks.",
            "outcome-1": "The forests are a limited success as the  many of the trees selected seem to die quite quickly, leading to a patchy feel to the forest. Some of the forests have been more resilient and the locals appreciate being close to nature.",
            "outcome-2": "The forests have been fairly successful and provide interesting talking points for the townspeople, though there are some concerns that the forests are becoming home to rats and feral pets.",
            "outcome-3": "The forests are a great success, providing local cool spaces in the middle of the town and providing opportunities for heat stress residents to engage with nature.",
            "img": "miyawaki.jpg",
            "local_url": "kb/interventions/interventions_24.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_24.html",
            "qr_code": "assets/interventions/interventions_24_qr.png"
        },
        {
            "type": "HP",
            "name": "Embrace <br> heat tourism",
            "desc": "The municipality is exploring the idea of capitalizing on its annual heatwave by branding the town as a destination for \u201cextreme heat tourism,\u201d aimed at attracting northern European tourists seeking high-temperature holiday experiences. <br>  <br> This strategy has the potential to boost tourism, stimulate the local economy, and create new jobs to support visitor services. However, prioritizing tourist infrastructure could risk shifting development focus away from the long-term needs of local residents.",
            "case_study": "",
            "EP": "4",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "-2",
            "outcome-heading": "Heat tourism <br> Outcomes",
            "outcome-0": "The town has become a tourist destination for booze-filled stag and hen parties, making the town a right mess and stretching the emergency services.",
            "outcome-1": "The town has developed its reputation as a winter sun destination, but the summer heatwaves make it too hot for many tourists, resulting in a highly seasonal industry and not really addressing the issue.",
            "outcome-2": "The town has become a popular destination, with tourists coming from around the world. This has created a boom for the locals, with many now working in tourism. ",
            "outcome-3": "The town has gained a reputation for being a great destination for discerning tourists throughout the year and it turns out that as much as tourists like the heat, they also like cool environments making the town liveable for all.",
            "img": "heat_tourism.jpg",
            "local_url": "kb/interventions/interventions_25.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_25.html",
            "qr_code": "assets/interventions/interventions_25_qr.png"
        },
        {
            "type": "HP",
            "name": "Create a heat  <br> knowledge base",
            "desc": "The municipality wants to develop a community website that offers residents practical information and support to help them cope with heatwaves and extreme heat events. <br>  <br> Research indicates that people often make poor decisions when dealing with extreme heat, particularly in cases of heat stress or heatstroke. By providing accessible, reliable information, the website can help residents make better-informed choices and respond more effectively during high-temperature conditions.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "2",
            "outcome-heading": "Heat knowledge base Outcomes",
            "outcome-0": "The project starts with a lot of fanfare, but the work is passed off to a low-cost bureau who have issues and produce a strange website that serves no-one.",
            "outcome-1": "The project is well-managed with a suitable design bureau delivering a great website. However, the ball is dropped when it comes to advertising  the site, with few residents event being aware that the site event exists. ",
            "outcome-2": "The project is delivered and residents are aware and using the website.  Residents are better able to prepare for the long summer heatwave and pass invaluable knowledge to visitors to the town.",
            "outcome-3": "The project is a great success with residents regularly engaging and contributing with the website, to the point that it has become nationally recognised with other towns starting to adopt a similar approach. ",
            "img": "dashboard.jpg",
            "local_url": "kb/interventions/interventions_26.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_26.html",
            "qr_code": "assets/interventions/interventions_26_qr.png"
        },
        {
            "type": "HP",
            "name": "Create a heat  <br> digital twin",
            "desc": "The municipality will develop a heatwave modelling digital twin to assess the likelihood and potential impacts of extreme heat events. This tool will support improved preparedness and inform long-term planning for heat resilience. <br>  <br> By integrating real-world data with advanced simulation models, the digital twin will generate valuable insights. Its effectiveness, however, will depend heavily on the quality of the data collected and the accuracy of the modelling.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "3",
            "outcome-heading": "Heat digital twin Outcomes",
            "outcome-0": "The project is handed off to a consultancy group who appear to have strange views about what constitutes appropriate heat data and models, resulting in a useless tool.",
            "outcome-1": "The digital twin generally works, but its AI seems to produce a lot of nightmare fuel, often predicting impossible scenarios. This makes it hard to trust the twin's outputs. ",
            "outcome-2": "The digital twin works well and is providing some good insights, not least  the predictive medium-term heat wave model. Allowing residents to plan accordingly. The municipality is happy and would like to develop it further.",
            "outcome-3": "The digital twin is providing the municipality with great insights and predictions, allowing heat protection activities to be far better targeted. Most residents don't notice, but the town is coping with long-term heat.",
            "img": "digital_twin.jpg",
            "local_url": "kb/interventions/interventions_27.html",
            "url": "https://arsinoe-serious-game.github.io/kb/interventions/interventions_27.html",
            "qr_code": "assets/interventions/interventions_27_qr.png"
        }
    ]
};

