let event_cards = 
[
    {
        "type": "EP",
        "name": "Extreme Economic Event",
        "heading-0": "What is an Extreme Economic Event",
        "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "heading-1": "What is an Extreme Economic Event?",
        "heading-2": "Heavy Econimic event",
        "heading-3": "Extreme Economic Event",
        "heading-4": "Lifetime Econimic Event",
        "desc-2": "event desc-1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "desc-3": "event desc-2Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "desc-4": "event desc-3Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "outcome-heading": "Extreme Economic Event Outcomes",
        "outcome-0": "severly under-preparedLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "outcome-1": "under-preparedLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "outcome-2": "fittingLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "outcome-3": "overkillLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "outcome-4": "extreme overkillLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
    },
    {
        "type": "BP",
        "name": "Extreme Biodiversity Event",
        "heading-0": "",
        "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "heading-1": "heading-1",
        "heading-2": "heading-2",
        "heading-3": "heading-3",
        "heading-4": "heading-4",
        "desc-2": "event desc-1",
        "desc-3": "event desc-2",
        "desc-4": "event desc-3",
        "outcome-heading": "Extreme Biodiversity Event Outcomes",
        "outcome-0": "severly under-prepared",
        "outcome-1": "under-prepared",
        "outcome-2": "fitting",
        "outcome-3": "overkill",
        "outcome-4": "extreme overkill"
    },
    {
        "type": "FP",
        "name": "Extreme Flood Event",
        "heading-0": "",
        "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "heading-1": "heading-1",
        "heading-2": "heading-2",
        "heading-3": "heading-3",
        "heading-4": "heading-4",
        "desc-2": "event desc-1",
        "desc-3": "event desc-2",
        "desc-4": "event desc-3",
        "outcome-heading": "Extreme Flood Event Outcomes",
        "outcome-0": "severly under-prepared",
        "outcome-1": "under-prepared",
        "outcome-2": "fitting",
        "outcome-3": "overkill",
        "outcome-4": "extreme overkill"
    },
    {
        "type": "DP",
        "name": "Extreme Drought Event",
        "heading-0": "",
        "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "heading-1": "heading-1",
        "heading-2": "heading-2",
        "heading-3": "heading-3",
        "heading-4": "heading-4",
        "desc-2": "event desc-1",
        "desc-3": "event desc-2",
        "desc-4": "event desc-3",
        "outcome-heading": "Extreme Drought Event Outcomes",
        "outcome-0": "severly under-prepared",
        "outcome-1": "under-prepared",
        "outcome-2": "fitting",
        "outcome-3": "overkill",
        "outcome-4": "extreme overkill"
    },
    {
        "type": "HP",
        "name": "Extreme Heat Event",
        "heading-0": "",
        "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "heading-1": "heading-1",
        "heading-2": "heading-2",
        "heading-3": "heading-3",
        "heading-4": "heading-4",
        "desc-2": "event desc-1",
        "desc-3": "event desc-2",
        "desc-4": "event desc-3",
        "outcome-heading": "Extreme Heat Event Outcomes",
        "outcome-0": "severly under-prepared",
        "outcome-1": "under-prepared",
        "outcome-2": "fitting",
        "outcome-3": "overkill",
        "outcome-4": "extreme overkill"
    }
];

