let game_data = 
{
    "personas": [
        {
            "type": "",
            "name": "Student",
            "desc": "You're a student and you're living and studying in the town. The local college is great, but you really like all the outdoor ammenities. <br>  <br> You're not sure about the future, you like the town but you need to have somewhere where you can get a good job and get on. <br>  <br> 12345 12345 12345 12345 12345 12345 12345 12345",
            "pos-1": "The idea of having money and freedom but are unsure how to get it.",
            "pos-2": "Surfing and Swim swimming (anything outdoorsy)  -  cowabunga baby!",
            "pos-3": " Not having to work",
            "neg-1": "Old people, they think they own the world.",
            "neg-2": "Being told what to do by adults who have messed the world up, which your generation now has to fix.",
            "neg-3": "Not being able to surf because of the sewage polluting the water!",
            "img": "student.jpg"
        },
        {
            "type": "",
            "name": "Single worker",
            "desc": "It's been a couple of years since you left education and have been finding your feet in the adult world of employment and responsibilities.",
            "pos-1": "Having a stable job with a decent wage and room to grow.",
            "pos-2": "Having nice things to do when I'm not at work.",
            "pos-3": "To be able to get on, buy a nicer flat with my partner and start putting down some roots.",
            "neg-1": "Lack of opportunities",
            "neg-2": "Struggling to make ends meet",
            "neg-3": "The state of the local environment, it all needs a good clean up.",
            "img": "single_worker.jpg"
        },
        {
            "type": "",
            "name": "Family",
            "desc": "You moved here when you got married to a local. It's a nice place, but it's not really home. However, you've got a good job and are putting down roots.",
            "pos-1": "My partner, they make it all worthwhile.",
            "pos-2": "Work opportunities, I couldn't do this work at home.",
            "pos-3": "Travel, there's lots of nice places to go to from here.",
            "neg-1": "The food and drink isn't the same as at home.",
            "neg-2": "Dealing with abuse, I'm from the other side of the channel 'mate'.",
            "neg-3": "The bureaucracy of living in a foreign country.",
            "img": "family.jpg"
        },
        {
            "type": "",
            "name": "Retiree",
            "desc": "You've retired to the town and want to enjoy yourself",
            "pos-1": "Activities that meet your needs as an active member of society. <br>  <br> ",
            "pos-2": "Opportunities to shop, socialize and be entertained.",
            "pos-3": "Easy transport links so you can get around and do the above.",
            "neg-1": "Change that adversely impacts you. <br> ",
            "neg-2": "Young people whinging about having it tough as you had it tough when you were young, and it didn't affect you much.",
            "neg-3": "Taxation as you've paid tax all your life and should be done with it now.",
            "img": "retiree.jpg"
        },
        {
            "type": "",
            "name": "Business owner",
            "desc": "You are a local shop keeper. You've managed your shop for years. It keeps you busy enough and financially secure, but not wealthy.",
            "pos-1": "Nice customers that make good purchases",
            "pos-2": "Tourists and holidaymakers that are keen to buy from me.",
            "pos-3": "Being apart of your local community",
            "neg-1": "The mall and out of town shopping taking away customers.",
            "neg-2": "High parking charges stopping people coming to town.",
            "neg-3": "The council changing things",
            "img": "business_owner.jpg"
        },
        {
            "type": "",
            "name": "Politician",
            "desc": "You are a local politician who got into politics to address injustice both locally and in the wider community.",
            "pos-1": "Policies that help all people",
            "pos-2": "Fair and just outcomes",
            "pos-3": "Karma",
            "neg-1": "Organisations and individuals that operate outside the law and outside the spirit of the law",
            "neg-2": "Short-termism",
            "neg-3": "Injustice",
            "img": "politician.jpg"
        }
    ],
    "events": [
        {
            "type": "EP",
            "name": "Economic Event",
            "heading-0": "What are economic events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Minor Event",
            "heading-2": "Average Event",
            "heading-3": "Extreme Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Economic Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        },
        {
            "type": "BP",
            "name": "Biodiversity Event",
            "heading-0": "What are biodiversity events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Minor Event",
            "heading-2": "Average Event",
            "heading-3": "Extreme Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Biodiversity Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        },
        {
            "type": "FP",
            "name": "Flood Event",
            "heading-0": "What are flood events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Minor Event",
            "heading-2": "Average Event",
            "heading-3": "Extreme Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Flood Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        },
        {
            "type": "DP",
            "name": "Drought Event",
            "heading-0": "What are drought events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Minor Event",
            "heading-2": "Average Event",
            "heading-3": "Extreme Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Drought Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        },
        {
            "type": "HP",
            "name": "Heat Event",
            "heading-0": "What are heat events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Minor Event",
            "heading-2": "Average Event",
            "heading-3": "Extreme Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Heat Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        }
    ],
    "text": [
        {
            "ID": "MAYOR_DETAIL",
            "text": "Welcome to the mayoral office. <br>  <br> Your role is to lead your team of citizens to ensure that they come to their decisions quickly and efficiently, while exploring the options in enough depth to make reasoned decisions.  <br>  <br> The reward for success is knowing that you have lead your citizens to make difficult decisions for the good of the town. <br>  <br>  <b> However, the price of failure is high. <b> "
        }
    ],
    "interventions": [
        {
            "type": "BP",
            "name": "Approve a fish farm",
            "desc": "Municipality has been approached to approve an offshore fish-farm. The farm will use modern methods to optimise fish yields.  <br>  <br> The farm will create local jobs in growing and processing the fish and will make good quality fish available   in the region and nationally. <br>  <br> However, fish farms are often criticised for creating monocultures, both for the fish and other water users as the farms are somewhat secretive about their methods of fish husbandry.",
            "case_study": "",
            "EP": "2",
            "BP": "-1",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "Water has been greatly contaminated by the operation of the farm. As a result, the natural marine life has been endangered by the release of pathogens and parasites",
            "outcome-1": "The fish farm attracts the local shark population resulting in  a surfer being attacked and wounded. ",
            "outcome-2": "The fish farms are operational and working well, creating jobs and adding fish to the local palette. ",
            "outcome-3": "The fish farming has been a great success! Many more people can afford to have locally supplied fresh fish, saving air miles. The income from the farming has been put back into the local community in educating local fishermen on sustainable fishing practice",
            "img": "fish_farm.jpg"
        },
        {
            "type": "BP",
            "name": "Approve a monofarm",
            "desc": "Municipality has been approached to approve a commercial super-farm on unused farmland. The farm will use modern methods to optimise crop production. <br>  <br> The farm will grow high yield, resistant crops and will create local jobs to support its operations. However, the high use of pesticides and high water consumption are likely to have negative impacts on biodiversity and water availability.  ",
            "case_study": "",
            "EP": "3",
            "BP": "-1",
            "FP": "0",
            "DP": "-1",
            "HP": "0",
            "outcome-0": "The crop chosen have proved extremely invasive and has spread to other farms and to peoples' gardens,  outcompeting native species and reducing local biodiversity.",
            "outcome-1": "The farm is producing bumper crop yields, but requires considerably more water than anticipated,  resulting in the local water company suggesting that people only shower once a week to save water.",
            "outcome-2": "The farm is producing an expected return and has created local jobs. The farm operators are careful to consider local biodiversity issues.",
            "outcome-3": "The farm is producing bumper crop yields and is managing to deliver them in harmony with the environment. To conserve water, the farm has developed a sophisticated irrigation system that has gained wide praise.",
            "img": "monofarm.jpg"
        },
        {
            "type": "BP",
            "name": "Citizen biodiversity",
            "desc": "Municipality has been approached to approve citizen science project to engage with members of the public to observe and record local fauna and flora using a mobile app. <br>  <br> Recording the environment will help researchers to understand the current state of the environment and capture its changes over time, to determine positive and negative biodiversity changes.",
            "case_study": "CS9",
            "EP": "0",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The project is a disaster! The app is developed by a consultancy with little understanding or interest in the project and product a buggy mess that nobody wants to use.",
            "outcome-1": "Theres's a small, but hardcore set of citizen users recording everything they can. This provides researchers with useful insights, but the project really needs more scale.",
            "outcome-2": "The project is a success, with the app being popular for school projects and wildlife enthusiasts. Although the app doesn't get broad appeal, it has a large enough user base to provide a lot of value.",
            "outcome-3": "The project is a great success, with residents becoming keen citizen scientists monitoring the wildlife they see around them. The data created by the project provides local biodiversity researchers with clear insights into the state of the environment allowing meaningful interventions to be followed.",
            "img": "dashboard.jpg"
        },
        {
            "type": "BP",
            "name": "Protect local biodiversity",
            "desc": "Municipality has been approached to approve the development of a wildlife park that specialises in protecting and supporting local flora and fauna. <br>  <br> The park will develop a breeding programme for rare fauna and look to release animals back into the local community to maintain viable stocks.",
            "case_study": "CS9",
            "EP": "1",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The project is a disaster! An initial breeding programme to strengthen the wolf community led to wolves growing out of control and decimated local pets.",
            "outcome-1": "Whilst the wildlife park has been able to breed endangered local animals, returning  them to their environments always proved difficult, leading to accusations that the park staff were incompetent. ",
            "outcome-2": "The project is a success, with the wildlife park receiving awards for its programmes. There's interest from the community, but it's felt that people would rather enjoy their days out.",
            "outcome-3": "The project is a great success, with rare native species being successfully reintroduced back into their natural habitats. The wildlife park visitor centres prove very popular with both locals and tourists, offering both the opportunity to see rare animals and to learn about biodiversity conservation.",
            "img": "image114.jpeg"
        },
        {
            "type": "BP",
            "name": "Legally protect local crops",
            "desc": "Municipality has been approached a local farming group to legally enshrine their locally produced crops using appropriate EU legislation. This would stop similar crops grown in other regions from using this regions' name.",
            "case_study": "CS9",
            "EP": "2",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The project is a disaster! The lawyers engaged by the municipality didn't understand the legal complexities of trademarking and lost their case, severely undermining the financial security of the farmers.",
            "outcome-1": "The project is a limited success. Whilst the crop has been protected, companies in other regions have been quick to relabel their ingredients and food products with new names. For many consumers, the difference are neither here nor there.",
            "outcome-2": "The project is a success, with crop protection in place, the farmers can operate securely knowing that their crop comes from this town.",
            "outcome-3": "The project is a great success, with the local crop being protected, farmers have built a heritage industry around their crop and the foodstuffs that can be made from it. This has made the town an attraction for tourists and gourmands looking for the 'real thing'. ",
            "img": "protect_local_crops.jpg"
        },
        {
            "type": "BP",
            "name": "Create a biodiversity knowledge base",
            "desc": "Municipality has been approached to develop a community website that will provide residents with useful information and support to help them through floods. <br>  <br> Research has shown that people are more stressed about the idea of being in a flood, rather than actually experiencing a flood. A website that provides support and information will help residents to become more knowledgeable.",
            "case_study": "CS9",
            "EP": "-1",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The project starts with a lot of fanfare, but the actual development work is passed off to a low-cost bureau who have a lot of trouble interpreting the brief, producing a strange website that serves no-one.",
            "outcome-1": "The project is well-managed with a suitable design bureau delivering a great website. However, the ball is dropped when it comes to advertising  the site, with few residents event being aware that the site event exists. ",
            "outcome-2": "The project is delivered and residents are aware and using the website. After an unseasonal flood, many residents cite the website as being a great resource for helping them to come to terms with flooding issues.",
            "outcome-3": "The project is a great success with residents regularly engaging and contributing with the website, to the point that it has become nationally recognised with other towns starting to adopt a similar approach. ",
            "img": "dashboard.jpg"
        },
        {
            "type": "BP",
            "name": "Create a biodiversity digital twin ",
            "desc": "Municipality will develop a biodiversity modelling digital twin to evaluate the likelihood and impact of activities that may be adverse to biodiversity, to build biodiversity resilience. <br>  <br> The digital twin will combine real-world data with simulation models to create insights, so it will be largely dependent on the quality of data collected and the accuracy of modelling.",
            "case_study": "",
            "EP": "-1",
            "BP": "3",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The project is handed off to a consultancy group who appear to have strange views about what constitutes appropriate biodiversity data and models, resulting in a useless tool.",
            "outcome-1": "The digital twin generally works, but the AI in it seem to produce a lot of nightmare fuel, often predicting extinction events. This makes it hard to trust the twin's outputs. ",
            "outcome-2": "The digital twin works well and is providing some good biodiversity strategy insights. The municipality is happy and would like to develop it further.",
            "outcome-3": "The digital twin is providing the municipality with great insights and predictions, allowing biodiversity protection activities to be far better targeted. Most residents don't notice, but biodiversity resilience is growing year on year.",
            "img": "digital_twin.jpg"
        },
        {
            "type": "DP",
            "name": "Approve reservoir construction ",
            "desc": "Municipality has been approached by the local water company to build a large reservoir in a local valley. The reservoir will capture the heavy winter rains, creating a more permeant water supply and reducing water scarcity in the summer months. <br>  <br> However, flooding the valley will impact local wildlife and stop fish migrations through the river that the reservoir is on.",
            "case_study": "",
            "EP": "-2",
            "BP": "-1",
            "FP": "2",
            "DP": "3",
            "HP": "0",
            "outcome-0": "The dam of the reservoir was made cheaply. In a heavy rainfall event the dam breaks, causing the water in the reservoir to flow downstream. Much of the town has been washed away.",
            "outcome-1": "Reduced flows downstream have affected local fish population. The local angling community are unhappy ",
            "outcome-2": "There was a serve drought in the summer. Luckily because of the reservoir there is enough water for the township. ",
            "outcome-3": "There was a serve drought in the summer. However, with the winter rains captured in the reservoir, there is easily enough water for all.",
            "img": "reservoir.jpg"
        },
        {
            "type": "DP",
            "name": "Approve a golf resort development",
            "desc": "Municipality has been approached by a premier resort developer to build a golf course resort on unused land.  <br> The course will attract wealthy golf enthusiasts and will spread wealth around the local area, with jobs and commercial opportunities for locals. <br>  <br> There is some concern that the course will require significant water resources to keep the course green and that the wealth of the members may stay in the gated community of the resort.",
            "case_study": "",
            "EP": "5",
            "BP": "-1",
            "FP": "0",
            "DP": "-1",
            "HP": "0",
            "outcome-0": "The project is a disaster! Whilst the course was constructed with no issues, running the resort requires a vast amount of water, with the water company suggesting that people only shower once a week to save water. ",
            "outcome-1": "The high resort fees tend to greatly limit the number of guests at any time and most just come to play golf and move on. There's not a lot of trickle down to the town, and if you didn't know the course was there, you probably wouldn't know about it.",
            "outcome-2": "The course is a success, though the high resort fees tend to keep the resort ticking over, giving a relaxed feel. The course has been good for the town, with jobs to support the course and the customers.",
            "outcome-3": "Golf tourists come from far and wide to play, and when they aren't playing a lot of them are visiting the town and spending money on good days and nights out.",
            "img": "golf_course.jpg"
        },
        {
            "type": "DP",
            "name": "Approve water delivery service",
            "desc": "The municipality is looking to ship in bottled water from another country in order to ameliorate problems with drinking water supply during drought conditions. <br>  <br> This will give the town a dependable supply of drinking water during the summer and it's much cheaper than updating the towns water collection and distribution network.  <br>  <br> However, the constant deliveries of bottled water will create traffic congestion. There's also the public relations issue that the municipality isn't prepared to solve its hard problems and just buys in solutions. ",
            "case_study": "",
            "EP": "-2",
            "BP": "0",
            "FP": "0",
            "DP": "2",
            "HP": "0",
            "outcome-0": "It's a disaster,  the water did not pass quality assurance and con not be consumed.  Instead the costly water is just being used for non-human use. ",
            "outcome-1": "The effects of a hot and dry summer have been offset through the water. While not a perfect solution, it has had a positive effect.",
            "outcome-2": "Despite a hot and dry summer, there are adequate water reserves and tourism benefits.",
            "outcome-3": "Despite a very hot and dry summer, there's more than enough water bringing in lots of tourists from other drier areas. ",
            "img": "water_delivery_service.png"
        },
        {
            "type": "DP",
            "name": "Install smart water meters",
            "desc": "The municipality is looking to install smart domestic water meters, allowing customers to view consumption and highlight leaks within their houses. <br>  <br> The meters allow customers to view their water consumption on a minute by minute basis, easily seeing the impact of showers, watering the gardening and running the washing machine and dishwasher. <br>  <br> However, customers often lose interest in their consumption once the novelty of a smart meter has worn off.",
            "case_study": "",
            "EP": "2",
            "BP": "0",
            "FP": "0",
            "DP": "2",
            "HP": "0",
            "outcome-0": "The project is a disaster! The smart metering app is buggy and often shows consumption that is unrelated to actual customer activity, resulting in customer having no confidence in the data. ",
            "outcome-1": "Meters have been installed, but the public response is apathetic. There is a perception that the meters are part of a 'surveillance society' that will use water consumption data to clamp down on civil liberties.",
            "outcome-2": "The smart water meters have been accepted by residents and water consumption is starting to show a reduction as enthusiastic residents look to minimise their consumption.",
            "outcome-3": "Residents love interacting with their smart water app and  consumption is at an all-time low. As a result, there is greatly decreased demand on the water distribution network allowing the water company to spend more time and resources addressing leakage.",
            "img": "smart_meters.jpg"
        },
        {
            "type": "DP",
            "name": "Smart irrigation programme",
            "desc": "The municipality is looking to work with local market gardeners to install smart irrigation systems to reduce water consumption. <br>  <br> The town has a large market garden industry which often places great demand on the water distribution network, with farmers preferring to water more than less, even though over watering can adversely effect crops. Using computers to access crop need should lead to less water consumption and allow currently marginal land to be used.",
            "case_study": "",
            "EP": "2",
            "BP": "0",
            "FP": "1",
            "DP": "2",
            "HP": "0",
            "outcome-0": "The project is a disaster! The smart irrigation platform is very buggy and is over watering many crops to the point of causing local floods.",
            "outcome-1": "Smart irrigation systems have been installed, with mixed results. Some farmers are reporting success, but many are reluctant to use them as they feel that they have a much better understanding of crop requirements.",
            "outcome-2": "The smart irrigation system seem to be working alright, though there have been a few teething issues. Most farmers are reporting that the system is working well for them, though a few have run into issues with over and under watering.",
            "outcome-3": "The smart irrigation systems are working well, with most farmers reporting both significant reductions in water requirements but also increases in yield. In some cases, marginal land is being returned to use.",
            "img": "smart_irrigation.jpg"
        },
        {
            "type": "DP",
            "name": "Create a drought dashboard",
            "desc": "Municipality has been approached to develop a community website that will provide residents with useful information and support to help them through floods. <br>  <br> Research has shown that people are more stressed about the idea of being in a flood, rather than actually experiencing a flood. A website that provides support and information will help residents to become more knowledgeable.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "0",
            "DP": "2",
            "HP": "0",
            "outcome-0": "The project starts with a lot of fanfare, but the actual development work is passed off to a low-cost bureau who have a lot of trouble interpreting the brief, producing a strange website that serves no-one.",
            "outcome-1": "The project is well-managed with a suitable design bureau delivering a great website. However, the ball is dropped when it comes to advertising  the site, with few residents event being aware that the site event exists. ",
            "outcome-2": "The project is delivered and residents are aware and using the website. After an unseasonal flood, many residents cite the website as being a great resource for helping them to come to terms with flooding issues.",
            "outcome-3": "The project is a great success with residents regularly engaging and contributing with the website, to the point that it has become nationally recognised with other towns starting to adopt a similar approach. ",
            "img": "dashboard.jpg"
        },
        {
            "type": "DP",
            "name": "Create a drought digital twin",
            "desc": "Municipality will develop a flood modelling digital twin to evaluate the likelihood and impact of potential flooding events, to better prepare for flooding and long-term planning for flood resilience. <br>  <br> The digital twin will combine real-world data with simulation models to create insights, so it will be largely dependent on the quality of data collected and the accuracy of modelling.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "0",
            "DP": "3",
            "HP": "0",
            "outcome-0": "The project is handed off to a consultancy group who appear to have strange views about what constitutes appropriate flood data and models, resulting in a useless tool.",
            "outcome-1": "The digital twin generally works, but the AI in it seem to produce a lot of nightmare fuel, often predicting impossible tsunamis on the coast. This makes it hard to trust the twin's outputs. ",
            "outcome-2": "The digital twin works well and is providing some good insights, not least a predictive flood model for coastal road closures. The municipality is happy and would like to develop it further.",
            "outcome-3": "The digital twin is providing the municipality with great insights and predictions, allowing flood protection activities to be far better targeted. Most residents don't notice, but the impact of flooding is decreasing year by year.",
            "img": "digital_twin.jpg"
        },
        {
            "type": "FP",
            "name": "Approve construction of a sea wall",
            "desc": "The community around the coastal road has been plagued by frequent sea floods, from high tides and onshore winds. This causes a great deal of disruption and leaves the area with costly flood damage and debris to clean up. <br>  <br> Building a sea wall will stop these flooding events. It will be a messy and disruptive construction process, but stopping the floods will help the area to stabilise and grow economically, even if it does ruin a good sea view.",
            "case_study": "",
            "EP": "2",
            "BP": "0",
            "FP": "2",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The project is a legal disaster area! Residents of nearby 'Cliff Heights' raise long and costly  objections as their district is being allowed to erode into the sea, resulting in the project being substantially delayed. ",
            "outcome-1": "The project completes on time and is warmly received despite ruining the view of the bay from the, now protected, coast road.\u200b",
            "outcome-2": "The project completes slightly ahead of time, early enough to protect the coastal road from some unseasonally high tides.",
            "outcome-3": "Shortly after the project completes, the town is buffeted a number of huge storms, the worst in living memory. Unlike previous storms, the coast road district doesn't flood saving the council by not having to perform a large clean-up. ",
            "img": "sea_wall.jpg"
        },
        {
            "type": "FP",
            "name": "Approve out-of-town leisure resort",
            "desc": "Municipality has been approached by a retail company to develop a large out of town retail and leisure park on unused land.  <br>  <br> The proposal is positive\u200bly regarded as it will provide long term employment for the area\u200b with many new jobs and attract a lot of visitors to the town. However, it's likely that the town centre will be hit financially with shoppers preferring to use the new out of town shops. In addition, the preferred development site is a meadow that's popular with the locals.",
            "case_study": "",
            "EP": "4",
            "BP": "-1",
            "FP": "-1",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The complex is a titanic success, so much so that there's gridlock in and around the town as everybody wants to go there making it impossible to travel anywhere.",
            "outcome-1": "The complex is a success, but heavy rains frequently flood the huge car parks and cause major traffic jams. ",
            "outcome-2": "The complex is a success with tenants that complement rather than compete with the town centre attractions. ",
            "outcome-3": "The complex is a real success and careful transport planning has enabled people from all over the region to attend films, gigs, and shows without causing chaos. ",
            "img": "lesiure_resort.jpg"
        },
        {
            "type": "FP",
            "name": "Approve nature-based flood protection",
            "desc": "Municipality has been approached by local university to host a beaver land management project to reduce river flooding. <br>  <br> The proposal is positively regarded as it positions the municipality as being forward looking by adopting nature-based solutions and the trial should be a low-cost activity. <br>  <br> However, as a research project, it's unproven and may go horribly wrong. There's also the consideration that beavers are an invasive species, so may adversely impact the local flora and fauna. ",
            "case_study": "",
            "EP": "1",
            "BP": "-1",
            "FP": "2",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The research is a disaster! The beavers have moved to the local arboretum and destroyed most of the rare saplings. The university abandoned the research as unworkable.",
            "outcome-1": "The beaver area suffers from a heavy rainstorm  resulting in beaver damn bursts and flooding in the downstream ",
            "outcome-2": "The beaver experiment is working well, and the university is working to increase size of the project, protecting more land. ",
            "outcome-3": "The beaver experiment is working well, with fewer floods. The beavers have been a local point of interest , drawing in beaver tourists and the sale of beaver plushies is through the roof. ",
            "img": "beavers.jpg"
        },
        {
            "type": "FP",
            "name": "Return seaside golf course to sea",
            "desc": "The town's seaside golf course is becoming submerged by global warming and high tides, with the municipality current spending a lot to protect it from nature.  Returning the course to the sea would allow the municipality to spend its limited budgets where they can have the biggest impact\u200b, support the creation of a wildlife wetland\u200b, and reduce motor traffic by that part of the shoreline. <br>  <br> However, such an action is likely to anger the golfers that current use the course and may be seen by townspeople as the municipality abandoning parts of the town to nature\u200b. ",
            "case_study": "",
            "EP": "1",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "As the golf course returns to nature, the town is hit by a 'once in a generation' storm with extreme tides that rush over the course and undermine the mainline rail track, causing it to be out of use for six months.",
            "outcome-1": "The course is returned to nature, but local golfers protest the decision by playing 'urban golf' in the town centre. ",
            "outcome-2": "As the course returns to wetland, it becomes a popular destination for firstly, birds and then bird watchers.",
            "outcome-3": "Hearing the news,  a former champion golfer buys the old typewriter factory and rejuvenates it into a high-quality course that keen golfers flock to, boosting tourism substantially. ",
            "img": "golf_course.jpg"
        },
        {
            "type": "FP",
            "name": "Engage in flood plain management",
            "desc": "Municipality has been approached to develop flood plain management for the local river, removing existing developments and allowing land to flood and store flood water.  <br>  <br> This should reduce flooding to downstream neighbourhoods\u200b and better management of the flood plans will facilitate the creation of new recreational activities and attract wildlife.\u200b <br>  <br> However, the flood plains will not remove flooding, which is likely to cause issues with stakeholders if not communicated properly.",
            "case_study": "",
            "EP": "-1",
            "BP": "1",
            "FP": "2",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The project is a disaster! There was a major flood , and a much larger area of land was flooded. Farming land has been destroyed and polluted waters flow through the town. ",
            "outcome-1": "The project appears to have been a success but key stakeholders seem unhappy with the outcomes and are currently blaming each other for any issues that arise.",
            "outcome-2": "The project appears to have been a success and stakeholders appear happy with the outcome. There appears to be less flooding after recent heavy storms and evidence of increased biodiversity .",
            "outcome-3": "The project was a great success. A rare species of butterfly has been seen in the area and bird species have increased. The downstream town also did not suffer flooding in the last heavy rainfall event",
            "img": "flood_plain.jpg"
        },
        {
            "type": "FP",
            "name": "Create a flood support website ",
            "desc": "Municipality has been approached to develop a community website that will provide residents with useful information and support to help them through floods. <br>  <br> Research has shown that people are more stressed about the idea of being in a flood, rather than actually experiencing a flood. A website that provides support and information will help residents to become more knowledgeable.",
            "case_study": "CS6",
            "EP": "-1",
            "BP": "0",
            "FP": "2",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The project starts with a lot of fanfare, but the actual development work is passed off to a low-cost bureau who have a lot of trouble interpreting the brief, producing a strange website that serves no-one.",
            "outcome-1": "The project is well-managed with a suitable design bureau delivering a great website. However, the ball is dropped when it comes to advertising  the site, with few residents event being aware that the site event exists. ",
            "outcome-2": "The project is delivered and residents are aware and using the website. After an unseasonal flood, many residents cite the website as being a great resource for helping them to come to terms with flooding issues.",
            "outcome-3": "The project is a great success with residents regularly engaging and contributing with the website, to the point that it has become nationally recognised with other towns starting to adopt a similar approach. ",
            "img": "dashboard.jpg"
        },
        {
            "type": "FP",
            "name": "Create a flooding digital twin",
            "desc": "Municipality will develop a flood modelling digital twin to evaluate the likelihood and impact of potential flooding events, to better prepare for flooding and long-term planning for flood resilience. <br>  <br> The digital twin will combine real-world data with simulation models to create insights, so it will be largely dependent on the quality of data collected and the accuracy of modelling.",
            "case_study": "CS8",
            "EP": "-1",
            "BP": "0",
            "FP": "3",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The project is handed off to a consultancy group who appear to have strange views about what constitutes appropriate flood data and models, resulting in a useless tool.",
            "outcome-1": "The digital twin generally works, but the AI in it seem to produce a lot of nightmare fuel, often predicting impossible tsunamis on the coast. This makes it hard to trust the twin's outputs. ",
            "outcome-2": "The digital twin works well and is providing some good insights, not least a predictive flood model for coastal road closures. The municipality is happy and would like to develop it further.",
            "outcome-3": "The digital twin is providing the municipality with great insights and predictions, allowing flood protection activities to be far better targeted. Most residents don't notice, but the impact of flooding is decreasing year by year.",
            "img": "digital_twin.jpg"
        },
        {
            "type": "HP",
            "name": "Approve installation of cool roofs",
            "desc": "Plans have been submitted to paint roofs with reflective paint, reducing the overall temperature in buildings and surrounding environment. <br>  <br> The project is generally a low-cost and non-invasive method of reducing urban heat. However, it only really benefits areas with long periods of very hot weather and is counter-productive in areas where solar panels have been installed.",
            "case_study": "CS1",
            "EP": "0",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "3",
            "outcome-0": "The project is a disaster! The painting contractors have ended up painting everything and destroying much of the towns domestic solar panel installations.",
            "outcome-1": "The roof painting phase of the project has been completed, but the expected hot weather and associated heat wave is noticeable by its absence. The townspeople reckon the municipality is just wasting money on vanity projects.",
            "outcome-2": "The roofs have been painted just in time for the summer heat wave and are having the desired effect. Rooms in painted houses feel cooler and the surrounding streets are far more pleasant to be in.",
            "outcome-3": "The roofs have been painted and there's a record breaking heatwave in the region. Unlike last year, it feels cooler in the streets, even though the weather is warmer. Residents are relived and thankful that their summers are liveable again.",
            "img": "cool_roofs.jpg"
        },
        {
            "type": "HP",
            "name": "Approve installation of firebreaks",
            "desc": "Plans have been submitted to Install fire breaks in the dry hinterland to reduce long-term damage of  heat-induced forest and scrub fires. <br>  <br> The breaks should contain fires and stop them spreading so widely. This should reduce reliance on the emergency services and reduce biodiversity loss. <br>  <br> However,  there are costs associated with installing and maintaining the breaks and the biodiversity impact of initially removing trees and scrubland.",
            "case_study": "",
            "EP": "1",
            "BP": "1",
            "FP": "0",
            "DP": "0",
            "HP": "1",
            "outcome-0": "The fire breaks have been a massive failure after a scrubland fire overcame the breaks and raged out of control until it burnt itself out.",
            "outcome-1": "The fire breaks are a success, but there is a lot of backlash from locals and tourists that the breaks have ruined the natural beaty of the hinterland.",
            "outcome-2": "High winds and a prolonged drought have hit the area, leading to wild fires breaking out across the region. However, the breaks are able to contain the fire to relatively small regions,  greatly reducing damage. ",
            "outcome-3": "The fire breaks have proved to be very capable in limiting the spread of wildfire. However, they've had the added bonus of becoming popular tourist hiking routes.",
            "img": "image9.jpeg"
        },
        {
            "type": "HP",
            "name": "Approve installation of green walls",
            "desc": "Municipality has been approached to install green walls on buildings in the town. The process should reduce local temperatures, making the buildings, and moreover, the streets around them cooler during the day, allowing residents to make more of the town's shops during the day. <br>  <br> However, the walls require a water supply to keep them green, otherwise, the plants will die creating bio and fire hazards.",
            "case_study": "CS1",
            "EP": "1",
            "BP": "1",
            "FP": "0",
            "DP": "0",
            "HP": "2",
            "outcome-0": "The green walls have not been adequately maintained. Clogged drainage systems have led to sewage overflows, making the buildings unpleasant to be around.",
            "outcome-1": "The green walls have been retrofitted and there has been no major setbacks. However, there has been an infestation of  aphids and spiders in one of the buildings which requires additional pest control.",
            "outcome-2": "The project was a success, many people have commented on the reduction of noise and stress within the workplace. ",
            "outcome-3": "The project was a great success. A local study has found that urban temperatures and air pollution have reduced, and less money has been spent on heating the buildings. ",
            "img": "green_walls.jpg"
        },
        {
            "type": "HP",
            "name": "Construct a Miyawaki Forest",
            "desc": "Municipality has been approached to install some small, but densely populated fast growing forests. <br>  <br> The tennis court sized forests can be planted almost anywhere, given their size, and provide the benefits of a forest right in the heart of the town, creating urban spaces that help mitigate the impacts of heat stress and connect people with nature. <br>  <br> However, the desire for fast growing forests can lead to the selection of tree species that are susceptible to disease and pests. <br> ",
            "case_study": "CS1",
            "EP": "0",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "2",
            "outcome-0": "Although fast growing, the tree species selected for the forest were highly susceptible to a local pest, resulting in many of the trees dying and becoming fire risks.",
            "outcome-1": "The forests are a limited success as the  many of the trees selected seem to die quite quickly, leading to a patchy feel to the forest. Some of the forests have been more resilient and the locals appreciate being close to nature.",
            "outcome-2": "The forests have been fairly successful and provide interesting talking points for the townspeople, though there are some concerns that the forests are becoming home to rats and feral pets.",
            "outcome-3": "The forests are a great success, providing local cool spaces in the middle of the town and providing opportunities for heat stress residents to 'touch grass' and engage with nature.",
            "img": ""
        },
        {
            "type": "HP",
            "name": "Embrace heat tourism",
            "desc": "Municipality is looking to make the most of its annual heatwave and brand the town for 'extreme heat tourism', to attract northern European tourists looking for hot holiday action.  <br>  <br> This should create a tourist boom and help the local economy by creating jobs to service tourist needs. However, supporting tourists may adversely affect the town by choosing developments that meet tourist, rather than local needs.",
            "case_study": "",
            "EP": "3",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "-2",
            "outcome-0": "The town has become a tourist destination for booze-filled stag and hen parties, making the town a right mess and stretching the emergency services to deal with all the issues.",
            "outcome-1": "The town has developed its reputation as a winter sun destination, but the summer heatwaves make it too hot for many tourists, resulting in a highly seasonal industry and not really addressing the issue.",
            "outcome-2": "The town has become a very popular summer heat destination, with tourists coming from around the world. This has created a boom for the locals, with many now working in tourism. ",
            "outcome-3": "The town has gained a reputation for being a great destination for discerning tourists throughout the year and it turns out that as much as tourists like the heat, they also like cool environments making the town liveable for all.",
            "img": "heat_tourism.jpg"
        },
        {
            "type": "HP",
            "name": "Create a heat knowledge base",
            "desc": "Municipality has been approached to develop a community website that will provide residents with useful information and support to help them through heat waves and extreme heat. <br>  <br> Research has shown that people often make bad choices about dealing with heat and will generally make bade decisions when dealing with heat stroke. A website that provides support and information will help residents to become more knowledgeable and make more appropriate decisions.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "2",
            "outcome-0": "The project starts with a lot of fanfare, but the actual development work is passed off to a low-cost bureau who have a lot of trouble interpreting the brief, producing a strange website that serves no-one.",
            "outcome-1": "The project is well-managed with a suitable design bureau delivering a great website. However, the ball is dropped when it comes to advertising  the site, with few residents event being aware that the site event exists. ",
            "outcome-2": "The project is delivered and residents are aware and using the website.  Residents are better able to prepare for the long summer heatwave and pass invaluable knowledge to visitors to the town.",
            "outcome-3": "The project is a great success with residents regularly engaging and contributing with the website, to the point that it has become nationally recognised with other towns starting to adopt a similar approach. ",
            "img": "dashboard.jpg"
        },
        {
            "type": "HP",
            "name": "Create a heat digital twin",
            "desc": "Municipality will develop a flood modelling digital twin to evaluate the likelihood and impact of potential flooding events, to better prepare for flooding and long-term planning for flood resilience. <br>  <br> The digital twin will combine real-world data with simulation models to create insights, so it will be largely dependent on the quality of data collected and the accuracy of modelling.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "3",
            "outcome-0": "The project is handed off to a consultancy group who appear to have strange views about what constitutes appropriate heat data and models, resulting in a useless tool.",
            "outcome-1": "The digital twin generally works, but the AI in it seem to produce a lot of nightmare fuel, often predicting impossible scenarios. This makes it hard to trust the twin's outputs. ",
            "outcome-2": "The digital twin works well and is providing some good insights, not least  the predictive medium-term heat wave model. Allowing residents to plan accordingly. The municipality is happy and would like to develop it further.",
            "outcome-3": "The digital twin is providing the municipality with great insights and predictions, allowing heat protection activities to be far better targeted. Most residents don't notice, but the town is being able to better cope with long-term heat.",
            "img": "digital_twin.jpg"
        }
    ]
};

