let game_data = 
{
    "personas": [
        {
            "type": "",
            "name": "Student",
            "desc": "You're a student and you're living and studying in the town. The local college is great, but you really like all the outdoor ammenities. <br>  <br> You're not sure about the future, you like the town but you need to have somewhere where you can get a good job and get on. <br>  <br> 12345 12345 12345 12345 12345 12345 12345 12345",
            "pos-1": "The idea of having money and freedom but are unsure how to get it.",
            "pos-2": "Surfing and Swim swimming (anything outdoorsy)  -  cowabunga baby!",
            "pos-3": " Not having to work",
            "neg-1": "Old people, they think they own the world.",
            "neg-2": "Being told what to do by adults who have messed the world up, which your generation now has to fix.",
            "neg-3": "Not being able to surf because of the sewage polluting the water!",
            "img": "student.jpg"
        },
        {
            "type": "",
            "name": "Single worker",
            "desc": "It's been a couple of years since you left education and have been finding your feet in the adult world of employment and responsibilities.",
            "pos-1": "Having a stable job with a decent wage and room to grow.",
            "pos-2": "Having nice things to do when I'm not at work.",
            "pos-3": "To be able to get on, buy a nicer flat with my partner and start putting down some roots.",
            "neg-1": "Lack of opportunities",
            "neg-2": "Struggling to make ends meet",
            "neg-3": "The state of the local environment, it all needs a good clean up.",
            "img": "single_worker.jpg"
        },
        {
            "type": "",
            "name": "Family",
            "desc": "You moved here when you got married to a local. It's a nice place, but it's not really home. However, you've got a good job and are putting down roots.",
            "pos-1": "My partner, they make it all worthwhile.",
            "pos-2": "Work opportunities, I couldn't do this work at home.",
            "pos-3": "Travel, there's lots of nice places to go to from here.",
            "neg-1": "The food and drink isn't the same as at home.",
            "neg-2": "Dealing with abuse, I'm from the other side of the channel 'mate'.",
            "neg-3": "The bureaucracy of living in a foreign country.",
            "img": "family.jpg"
        },
        {
            "type": "",
            "name": "Retiree",
            "desc": "You've retired to the town and want to enjoy yourself",
            "pos-1": "Activities that meet your needs as an active member of society. <br>  <br> ",
            "pos-2": "Opportunities to shop, socialize and be entertained.",
            "pos-3": "Easy transport links so you can get around and do the above.",
            "neg-1": "Change that adversely impacts you. <br> ",
            "neg-2": "Young people whinging about having it tough as you had it tough when you were young, and it didn't affect you much.",
            "neg-3": "Taxation as you've paid tax all your life and should be done with it now.",
            "img": "retiree.jpg"
        },
        {
            "type": "",
            "name": "Business owner",
            "desc": "You are a local shop keeper. You've managed your shop for years. It keeps you busy enough and financially secure, but not wealthy.",
            "pos-1": "Nice customers that make good purchases",
            "pos-2": "Tourists and holidaymakers that are keen to buy from me.",
            "pos-3": "Being apart of your local community",
            "neg-1": "The mall and out of town shopping taking away customers.",
            "neg-2": "High parking charges stopping people coming to town.",
            "neg-3": "The council changing things",
            "img": "business_owner.jpg"
        },
        {
            "type": "",
            "name": "Politician",
            "desc": "You are a local politician who got into politics to address injustice both locally and in the wider community.",
            "pos-1": "Policies that help all people",
            "pos-2": "Fair and just outcomes",
            "pos-3": "Karma",
            "neg-1": "Organisations and individuals that operate outside the law and outside the spirit of the law",
            "neg-2": "Short-termism",
            "neg-3": "Injustice",
            "img": "politician.jpg"
        }
    ],
    "events": [
        {
            "type": "EP",
            "name": "Economic Event",
            "heading-0": "What are economic events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Minor Event",
            "heading-2": "Average Event",
            "heading-3": "Extreme Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Economic Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        },
        {
            "type": "BP",
            "name": "Biodiversity Event",
            "heading-0": "What are biodiversity events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Minor Event",
            "heading-2": "Average Event",
            "heading-3": "Extreme Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Biodiversity Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        },
        {
            "type": "FP",
            "name": "Flood Event",
            "heading-0": "What are flood events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Minor Event",
            "heading-2": "Average Event",
            "heading-3": "Extreme Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Flood Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        },
        {
            "type": "DP",
            "name": "Drought Event",
            "heading-0": "What are drought events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Minor Event",
            "heading-2": "Average Event",
            "heading-3": "Extreme Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Drought Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        },
        {
            "type": "HP",
            "name": "Heat Event",
            "heading-0": "What are heat events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Minor Event",
            "heading-2": "Average Event",
            "heading-3": "Extreme Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Heat Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        }
    ],
    "text": [
        {
            "ID": "MAYOR_DETAIL",
            "text": "Welcome to the mayoral office. <br>  <br> Your role is to lead your team of citizens to ensure that they come to their decisions quickly and efficiently, while exploring the options in enough depth to make reasoned decisions.  <br>  <br> The reward for success is knowing that you have lead your citizens to make difficult decisions for the good of the town. <br>  <br>  <b> However, the price of failure is high. <b> "
        }
    ],
    "interventions": [
        {
            "type": "BP",
            "name": "Approve a fish farm",
            "desc": "Municipality has been approached to approve an offshore fish-farm. The farm will use modern methods to optimise fish yields. ",
            "case_study": "",
            "EP": "2",
            "BP": "-1",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "Water has been greatly contaminated by the operation of the farm. As a result, the natural marine life has been endangered by the release of pathogens and parasites",
            "outcome-1": "The fish farm attracts the local shark population resulting in  a surfer being attacked and wounded. ",
            "outcome-2": "The fish farms are operational and working well, creating jobs and adding fish to the local palette. ",
            "outcome-3": "The fish farming has been a great success! Many more people can afford to have locally supplied fresh fish, saving air miles. The income from the farming has been put back into the local community in educating local fishermen on sustainable fishing practice",
            "img": "fish_farm.jpg"
        },
        {
            "type": "BP",
            "name": "Approve a monofarm",
            "desc": "Municipality has been approached to approve a commercial super-farm on unused farmland. The farm will use modern methods to optimise crop production. ",
            "case_study": "",
            "EP": "3",
            "BP": "-1",
            "FP": "0",
            "DP": "-1",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "monofarm.jpg"
        },
        {
            "type": "BP",
            "name": "citizen MINKA (CS9)",
            "desc": "This is MINKA. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "",
            "EP": "0",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "dashboard.jpg"
        },
        {
            "type": "BP",
            "name": "Create a biodiversity digital twin ",
            "desc": "Add a digital twin to do digital twin stuff",
            "case_study": "",
            "EP": "-1",
            "BP": "3",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "digital_twin.jpg"
        },
        {
            "type": "BP",
            "name": "Create a biodiversity knowledge base (CS9)",
            "desc": "This sounds like MINKA, but is part of the Sardinia farmer dashboard - although that's ET rather than BD",
            "case_study": "",
            "EP": "-1",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "dashboard.jpg"
        },
        {
            "type": "BP",
            "name": "Protect local biodiversity (CS9)",
            "desc": "This sounds like MINKA. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "",
            "EP": "0",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": ""
        },
        {
            "type": "BP",
            "name": "protect local crops",
            "desc": "This is the Sardinia durum wheat scheme. Should strengthen the local farming community and protect local crop types",
            "case_study": "",
            "EP": "2",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "protect_local_crops.jpg"
        },
        {
            "type": "DP",
            "name": "Approve a golf resort development",
            "desc": "Municipality has been approached by a premier resort developer to build a golf course resort on unused land. ",
            "case_study": "",
            "EP": "5",
            "BP": "-1",
            "FP": "0",
            "DP": "-1",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "golf_course.jpg"
        },
        {
            "type": "DP",
            "name": "Approve reservoir construction ",
            "desc": "Municipality has been approached by the local water company to build a large reservoir in a local valley.",
            "case_study": "",
            "EP": "-2",
            "BP": "-1",
            "FP": "2",
            "DP": "3",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "reservoir.jpg"
        },
        {
            "type": "DP",
            "name": "Approve water delivery service",
            "desc": "The municipality is looking to ship in bottled water to ameliorate problems with drinking water supply during drought conditions.",
            "case_study": "",
            "EP": "-2",
            "BP": "0",
            "FP": "0",
            "DP": "2",
            "HP": "0",
            "outcome-0": " The water quality did not pass the needed checks, and none of the water can be used. ",
            "outcome-1": "Traffic in the town has become much worse due to transporting all the water. There are potholes everywhere and you have some very disgruntled locals.",
            "outcome-2": "The effects of a hot and dry summer have been offset through the water. While not a perfect solution, it has had a positive effect.",
            "outcome-3": "Despite a very hot and dry summer, there's more than enough water bringing in lots of tourists from other drier areas. ",
            "img": "water_delivery_service.png"
        },
        {
            "type": "DP",
            "name": "Create a drought dashboard",
            "desc": "As per CS5. Municipality will install a platform to monitor climate data in order to better understand drought events.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "0",
            "DP": "2",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "dashboard.jpg"
        },
        {
            "type": "DP",
            "name": "Create a drought digital twin",
            "desc": "Municipality will install a drought modelling digital twin to evaluate the likelihood and impact of drought scenarios, to better prepare for dry periods and long-term planning for drought resilience.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "0",
            "DP": "3",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "digital_twin.jpg"
        },
        {
            "type": "DP",
            "name": "Install smart water meters",
            "desc": "The municipality is looking to install smart water meters, allowing customers to view consumption and highlight leaks within their houses.",
            "case_study": "",
            "EP": "2",
            "BP": "0",
            "FP": "0",
            "DP": "2",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "smart_meters.jpg"
        },
        {
            "type": "DP",
            "name": "Smart irrigation programme",
            "desc": "The municipality is looking to work with local market gardeners to install smart irrigation systems to reduce water consumption.",
            "case_study": "",
            "EP": "2",
            "BP": "0",
            "FP": "1",
            "DP": "2",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "smart_irrigation.jpg"
        },
        {
            "type": "FP",
            "name": "Approve construction of a sea wall",
            "desc": "12345 12345 12345 12345 12345 12345 12345 12345 12345 12345 <br> The coast road community is plagued by coastal over topping, causing disruption and flooding local shops and houses. <br>  <br> The sea wall should minimise flooding risk to the local community, reduce flood clean-up costs and iIncrease investment into the area.  <br>  <br> However, there will be substaintial isruption during building works and the wall will lessen the view of the bay.",
            "case_study": "",
            "EP": "2",
            "BP": "0",
            "FP": "2",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The project is a disaster! Residents of nearby cliff heights raise a long and costly legal objections as their district is being allowed to erode into the sea, resulting in the project being substantially delayed. ",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "Shortly after the project completes, there is a huge storm. Unlike previous storms, the coast road district doesn't flood saving the council by not having to perform a large clean-up. ",
            "img": "sea_wall.jpg"
        },
        {
            "type": "FP",
            "name": "Approve out-of-town leisure resort",
            "desc": "Municipality has been approached by a retail company to develop a large out-of-town retail and leisure park on unused land. ",
            "case_study": "",
            "EP": "4",
            "BP": "-1",
            "FP": "-1",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The complex is a titanic success, so much so that there's gridlock in and around the town as everybody wants to go there making it impossible to travel anywhere.",
            "outcome-1": "The complex is a success, but heavy rains frequently flood the huge car parks ",
            "outcome-2": "The complex is a success with tenants that complement rather than compete with the town centre attractions. ",
            "outcome-3": "The complex is a real success and careful transport planning has enabled people from all over the region to attend films, gigs, and shows without causing chaos. ",
            "img": "lesiure_resort.jpg"
        },
        {
            "type": "FP",
            "name": "Approve nature-based flood protection",
            "desc": "Municipality has been approached by a university to host a beaver land management project to reduce river flooding.",
            "case_study": "",
            "EP": "1",
            "BP": "-1",
            "FP": "2",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The research is a disaster! The beavers have moved to the local arboretum and destroyed most of the rare saplings. The university abandoned the research as unworkable.",
            "outcome-1": "The beaver area suffers from a heavy rainstorm  resulting in beaver damn bursts and flooding in the downstream ",
            "outcome-2": "The beaver experiment is working well, and the university is working to increase size of the project, protecting more land. ",
            "outcome-3": "The beaver experiment is working well, with fewer floods. The beavers have been a local point of interest , drawing in beaver tourists and the sale of beaver plushies is through the roof. ",
            "img": "beavers.jpg"
        },
        {
            "type": "FP",
            "name": "Return seaside golf course to sea",
            "desc": "The municipality will stop flood protecting the old sea-side golf course and return it to nature as a coastal wetland.",
            "case_study": "",
            "EP": "1",
            "BP": "2",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "As the golf course returns to nature, the town is hit by a 'once in a generation' storm with extreme tides that rush over the course and undermine the mainline rail track, causing it to be out of use for six months.",
            "outcome-1": "Local golfers protest the decision by playing 'urban golf' in the town centre.  ",
            "outcome-2": "As the course returns to wetland, it becomes a popular destination for firstly, birds and then bird watchers.",
            "outcome-3": "Hearing the news,  a former champion golfer buys the old typewriter factory and rejuvenates it into a high-quality course that keen golfers flock to, boosting tourism substantially. ",
            "img": "golf_course.jpg"
        },
        {
            "type": "FP",
            "name": "Create a flood support website (CS6)",
            "desc": "As per CS6. Municipality will install a platform to support citizens with support and guidance for flooding.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "2",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "dashboard.jpg"
        },
        {
            "type": "FP",
            "name": "Create a flooding digital twin",
            "desc": "As per CS6, CS8. Municipality will install a flood modelling digital twin to evaluate the likelihood and impact of potential flooding events, to better prepare for flooding and long-term planning for flood resilience.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "3",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "digital_twin.jpg"
        },
        {
            "type": "FP",
            "name": "Engage in flood plain management",
            "desc": "Municipality has been approached to develop flood plain management for the local river, removing existing developments and allowing land to flood and store flood water. ",
            "case_study": "",
            "EP": "-1",
            "BP": "1",
            "FP": "2",
            "DP": "0",
            "HP": "0",
            "outcome-0": "The project is a disaster! There was a major flood , and a much larger area of land was flooded. Farming land has been destroyed and polluted waters flow through the town. ",
            "outcome-1": "",
            "outcome-2": "",
            "outcome-3": " The project was a success. A rare species of butterfly has been seen in the area and bird species have increased. The downstream town also did not suffer flooding in the last heavy rainfall event",
            "img": "flood_plain.jpg"
        },
        {
            "type": "HP",
            "name": "Approve installation of cool roofs (CS1)",
            "desc": "Plans have been submitted to paint roofs with reflective paint, reducing the overall temperature in buildings and surrounding environment.",
            "case_study": "",
            "EP": "0",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "3",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "cool_roofs.jpg"
        },
        {
            "type": "HP",
            "name": "Approve installation of firebreaks",
            "desc": "Install fire breaks in the dry hinterland to reduce long-term damage of  heat-induced forest and scrub fires.",
            "case_study": "",
            "EP": "2",
            "BP": "1",
            "FP": "0",
            "DP": "0",
            "HP": "1",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": ""
        },
        {
            "type": "HP",
            "name": "Approve installation of green walls (CS1)",
            "desc": "Green walls will lower urban temperatures making towns more habitable, increasing footfall and revenue.",
            "case_study": "",
            "EP": "1",
            "BP": "1",
            "FP": "0",
            "DP": "0",
            "HP": "2",
            "outcome-0": "The green walls have not been adequately maintained. Clogged drainage systems have led to sewage overflows and spills and created a right old stink in and around the buildings.",
            "outcome-1": "There has been an infestation of  aphids and spiders in one of the buildings and requires additional pest control.",
            "outcome-2": "The project was a success, many people have commented on the reduction of noise and stress within the workplace. ",
            "outcome-3": "The project was a great success. A local study has found that urban temperatures and air pollution have reduced, and less money has been spent on heating the buildings. ",
            "img": "green_walls.jpg"
        },
        {
            "type": "HP",
            "name": "Create a heat knowledge base",
            "desc": "Municipality will install a citizen knowledge base to provide helpful support for dealing with prolonged high temperatures.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "2",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "dashboard.jpg"
        },
        {
            "type": "HP",
            "name": "Create a heat digital twin",
            "desc": "Municipality will install a climate modelling digital twin to evaluate the likelihood and impact of extreme temperature scenarios, to better prepare for very hot periods and long-term planning for heat resilience.",
            "case_study": "",
            "EP": "-1",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "3",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "digital_twin.jpg"
        },
        {
            "type": "HP",
            "name": "Construct a Miyawaki Forest (CS1)",
            "desc": " <b> Build a Miyawaki forest </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "case_study": "",
            "EP": "0",
            "BP": "1",
            "FP": "0",
            "DP": "0",
            "HP": "1",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": ""
        },
        {
            "type": "HP",
            "name": "Embrace heat tourism",
            "desc": "Municipality is looking to brand the town for 'extreme heat tourism', to attract northern European tourists looking for hot holiday action. ",
            "case_study": "",
            "EP": "3",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "-1",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "heat_tourism.jpg"
        }
    ]
};

