let game_data = 
{
    "personas": [
        {
            "type": "",
            "name": "Student",
            "desc": "You're a student and you're living and studying in the town. The local college is great, but you really like all the outdoor ammenities. <br>  <br> You're not sure about the future, you like the town but you need to have somewhere where you can get a good job and get on. <br>  <br> 12345 12345 12345 12345 12345 12345 12345 12345",
            "pos-1": "The idea of having money and freedom but are unsure how to get it.",
            "pos-2": "Surfing and Swim swimming (anything outdoorsy)  -  cowabunga baby!",
            "pos-3": " Not having to work",
            "neg-1": "Old people, they think they own the world.",
            "neg-2": "Being told what to do by adults who have messed the world up, which your generation now has to fix.",
            "neg-3": "Not being able to surf because of the sewage polluting the water!",
            "img": "student.jpg"
        },
        {
            "type": "",
            "name": "Single worker",
            "desc": "It's been a couple of years since you left education and have been finding your feet in the adult world of employment and responsibilities.",
            "pos-1": "Having a stable job with a decent wage and room to grow.",
            "pos-2": "Having nice things to do when I'm not at work.",
            "pos-3": "To be able to get on, buy a nicer flat with my partner and start putting down some roots.",
            "neg-1": "Lack of opportunities",
            "neg-2": "Struggling to make ends meet",
            "neg-3": "The state of the local environment, it all needs a good clean up.",
            "img": "single_worker.jpg"
        },
        {
            "type": "",
            "name": "Family",
            "desc": "You moved here when you got married to a local. It's a nice place, but it's not really home. However, you've got a good job and are putting down roots.",
            "pos-1": "My partner, they make it all worthwhile.",
            "pos-2": "Work opportunities, I couldn't do this work at home.",
            "pos-3": "Travel, there's lots of nice places to go to from here.",
            "neg-1": "The food and drink isn't the same as at home.",
            "neg-2": "Dealing with abuse, I'm from the other side of the channel 'mate'.",
            "neg-3": "The bureaucracy of living in a foreign country.",
            "img": "family.jpg"
        },
        {
            "type": "",
            "name": "Retiree",
            "desc": "You've retired to the town and want to enjoy yourself",
            "pos-1": "Activities that meet your needs as an active member of society. <br>  <br> ",
            "pos-2": "Opportunities to shop, socialize and be entertained.",
            "pos-3": "Easy transport links so you can get around and do the above.",
            "neg-1": "Change that adversely impacts you. <br> ",
            "neg-2": "Young people whinging about having it tough as you had it tough when you were young, and it didn't affect you much.",
            "neg-3": "Taxation as you've paid tax all your life and should be done with it now.",
            "img": "retiree.jpg"
        },
        {
            "type": "",
            "name": "Business owner",
            "desc": "You are a local shop keeper. You've managed your shop for years. It keeps you busy enough and financially secure, but not wealthy.",
            "pos-1": "Nice customers that make good purchases",
            "pos-2": "Tourists and holidaymakers that are keen to buy from me.",
            "pos-3": "Being apart of your local community",
            "neg-1": "The mall and out of town shopping taking away customers.",
            "neg-2": "High parking charges stopping people coming to town.",
            "neg-3": "The council changing things",
            "img": "business_owner.jpg"
        },
        {
            "type": "",
            "name": "Politician",
            "desc": "You are a local politician who got into politics to address injustice both locally and in the wider community.",
            "pos-1": "Policies that help all people",
            "pos-2": "Fair and just outcomes",
            "pos-3": "Karma",
            "neg-1": "Organisations and individuals that operate outside the law and outside the spirit of the law",
            "neg-2": "Short-termism",
            "neg-3": "Injustice",
            "img": "politician.jpg"
        }
    ],
    "events": [
        {
            "type": "EP",
            "name": "Economic Event",
            "heading-0": "What are extreme economic events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Heavy event",
            "heading-2": "Extreme Event",
            "heading-3": "Lifetime Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Economic Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        },
        {
            "type": "BP",
            "name": "Biodiversity Event",
            "heading-0": "What are extreme biodiversity events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Heavy event",
            "heading-2": "Extreme Event",
            "heading-3": "Lifetime Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Biodiversity Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        },
        {
            "type": "FP",
            "name": "Flood Event",
            "heading-0": "What are extreme flood events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Heavy event",
            "heading-2": "Extreme Event",
            "heading-3": "Lifetime Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Flood Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        },
        {
            "type": "DP",
            "name": "Drought Event",
            "heading-0": "What are extreme drought events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Heavy event",
            "heading-2": "Extreme Event",
            "heading-3": "Lifetime Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Drought Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        },
        {
            "type": "HP",
            "name": "Heat Event",
            "heading-0": "What are extreme heat events?",
            "desc-0": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "heading-1": "Heavy event",
            "heading-2": "Extreme Event",
            "heading-3": "Lifetime Event",
            "desc-1": "event desc-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-2": "event desc-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "desc-3": "event desc-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-heading": "Heat Event Outcomes",
            "outcome-0": "severely under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-1": "under-prepared. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-2": "fitting. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-3": "overkill. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "outcome-4": "extreme overkill.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
        }
    ],
    "text": [
        {
            "ID": "MAYOR_DETAIL",
            "text": "Welcome to the mayoral office. <br>  <br> Your role is to lead your team of citizens to ensure that they come to their decisions quickly and efficiently, while exploring the options in enough depth to make reasoned decisions.  <br>  <br> The reward for success is knowing that you have lead your citizens to make difficult decisions for the good of the town. <br>  <br>  <b> However, the price of failure is high. <b> "
        }
    ],
    "interventions": [
        {
            "type": "FP",
            "name": "ENOVA BioSense",
            "desc": " <b> Water quality biosensor </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS6B",
            "EP": "2",
            "BP": "-1",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "FP",
            "name": "GoVocal",
            "desc": " <b> Citizen engagement </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS7",
            "EP": "0",
            "BP": "0",
            "FP": "1",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "FP",
            "name": "Saferplaces",
            "desc": " <b> Flood risk DT (satellite & climate data -> AI) </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS7",
            "EP": "0",
            "BP": "0",
            "FP": "1",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "FP",
            "name": "Crisis workshop",
            "desc": " <b> crisis management serious game workshop </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS7",
            "EP": "0",
            "BP": "0",
            "FP": "1",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "FP",
            "name": "Ripple Effects",
            "desc": " <b> empowering the community </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS8",
            "EP": "0",
            "BP": "0",
            "FP": "1",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "FP",
            "name": "ARGOS",
            "desc": " <b> Dashboard / digital twin for decision making / early warning of weather events </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS8",
            "EP": "0",
            "BP": "0",
            "FP": "1",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "HP",
            "name": "Kausal Platform",
            "desc": " <b> SaaS platform to manage implementation of climate plans </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS1",
            "EP": "0",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "1",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "HP",
            "name": "Singular Ribbon",
            "desc": " <b> Plants on wires in town </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS1",
            "EP": "0",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "1",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "HP",
            "name": "Tiny Forest",
            "desc": " <b> A Miyawaki forest </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS1",
            "EP": "0",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "1",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "HP",
            "name": "FiClima",
            "desc": " <b> Saas dashboard for high resolution climate data </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS5",
            "EP": "0",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "1",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "HP",
            "name": "Farmer dashboard",
            "desc": " <b> Dashboard knowledge base for farmers in Sardinia </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS9",
            "EP": "0",
            "BP": "0",
            "FP": "0",
            "DP": "0",
            "HP": "1",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "DP",
            "name": "IRRIBIGDATA",
            "desc": " <b> Efficient irigation </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS3",
            "EP": "0",
            "BP": "0",
            "FP": "0",
            "DP": "1",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "DP",
            "name": "Tip Tap",
            "desc": " <b> Tap water firendly cycle route along the Main </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS3",
            "EP": "0",
            "BP": "0",
            "FP": "0",
            "DP": "1",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "DP",
            "name": "Water4All",
            "desc": " <b> Lake level estimation from groundwater (saas?) </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS4",
            "EP": "0",
            "BP": "0",
            "FP": "0",
            "DP": "1",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "DP",
            "name": "Integrated Water Resillence System",
            "desc": " <b> Tech/data-driven approach to monitor Ohrid and Prespa lakes </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS4",
            "EP": "0",
            "BP": "0",
            "FP": "0",
            "DP": "1",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "DP",
            "name": "Proverse",
            "desc": " <b> Saas / platform for climate change and biofiltration on Danube delta (sounds like a DT) </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS6R",
            "EP": "0",
            "BP": "0",
            "FP": "0",
            "DP": "1",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "BP",
            "name": "?",
            "desc": " <b> Nothing presented at the plenary </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS6I",
            "EP": "0",
            "BP": "1",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "BP",
            "name": "Bread certification",
            "desc": " <b> Certify local bread for local people </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS9",
            "EP": "0",
            "BP": "1",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "BP",
            "name": "Black Sea Platform",
            "desc": " <b> SaaS / dashboard to monitor air quality </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS6T",
            "EP": "0",
            "BP": "1",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "BP",
            "name": "CLEVEL TOOL",
            "desc": "A climate change impact monitoring system that integrates with the data from the SAMOA system (which provides oceanic variable predictions for the Port of Valencia) , meteorological variables from both the port's own stations and AEMET (Spanish Weather Agency). Additionally, terminals operating in the port will be equipped with a user-friendly tool, a mobile app, allowing them to quickly and clearly report any events (shutdowns, damages, delays, etc.) caused by climatic conditions. This way, real-time data on the evolution of variables and their impacts on port infrastructures and operations will be available. This, in turn, will assist port authorities in obtaining the most accurate future climate predictions, facilitating proper sizing of new infrastructures and determining when adjustments to current facilities are necessary.",
            "case_study": "CS2",
            "EP": "0",
            "BP": "1",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "BP",
            "name": "DIORAMA",
            "desc": " <b> Air quality Saas </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS2",
            "EP": "0",
            "BP": "1",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        },
        {
            "type": "BP",
            "name": "EMBIO DIAGNOSTICS",
            "desc": " <b> Environmental SaaS </b>  <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "case_study": "CS2",
            "EP": "0",
            "BP": "1",
            "FP": "0",
            "DP": "0",
            "HP": "0",
            "outcome-0": "out-1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-1": "out-2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-2": "out-3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "outcome-3": "out-4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "img": "beavers.jpg"
        }
    ]
};

